export interface ExportOptions {
    format: 'pdf' | 'text' | 'whatsapp';
    recipientType: 'patient' | 'doctor';
    patientName: string;
    professionalName: string;
}

export const logExportEvent = async (options: ExportOptions) => {
    // In a real app, this would use Supabase Audit Log
    console.log(`[AUDIT] Export generated by ${options.professionalName} for ${options.patientName} (${options.format}/${options.recipientType})`);

    // Stub for AuditLog
    // await supabase.from('audit_logs').insert({...})
};

export const generateWhatsAppText = (patientName: string, reportSummary: string, link?: string) => {
    const timeOfDay = new Date().getHours() < 12 ? 'Bom dia' : 'Boa tarde';
    return `${timeOfDay}, ${patientName}.

Aqui é da FisioFlow. Segue o resumo da sua avaliação biomecânica:

"${reportSummary}"

${link ? `Acesse o relatório completo aqui: ${link}` : 'O relatório completo em PDF foi enviado em anexo.'}

Qualquer dúvida, estamos à disposição.
Atenciosamente,
FisioFlow`;
};

export const generateDoctorLetterText = (patientName: string, professionalName: string, findings: string[], evolution: string) => {
    return `Prezado(a) Colega,

Encaminho relatório de avaliação biomecânica do paciente ${patientName}.

RESUMO FUNCIONAL:
Observou-se ${evolution.toLowerCase()}.

ACHADOS RELEVANTES:
${findings.map(f => `- ${f}`).join('\n')}

Seguimos à disposição para discussão do caso.

Atenciosamente,
${professionalName}
Fisioterapeuta`;
};
