/**
 * Report Export Service - Migrated to Firebase
 *
 * Migration from Supabase to Firebase:
 * - supabase.from('audit_logs').insert() → Firestore addDoc()
 */

import { getFirebaseDb } from '@/integrations/firebase/app';
import { collection, addDoc } from 'firebase/firestore';

const db = getFirebaseDb();

export interface ExportOptions {
    format: 'pdf' | 'text' | 'whatsapp';
    recipientType: 'patient' | 'doctor';
    patientName: string;
    professionalName: string;
}

export const logExportEvent = async (options: ExportOptions) => {
    try {
        // Log to Firestore audit_logs collection
        const auditLog = {
            action: 'export_report',
            professional_name: options.professionalName,
            patient_name: options.patientName,
            format: options.format,
            recipient_type: options.recipientType,
            timestamp: new Date().toISOString(),
            user_id: null, // Could add auth user ID if available
        };

        await addDoc(collection(db, 'audit_logs'), auditLog);

        console.log(`[AUDIT] Export logged to Firestore: ${options.professionalName} → ${options.patientName} (${options.format}/${options.recipientType})`);
    } catch (error) {
        console.error('[reportExportService] Error logging export event:', error);
        // Continue execution even if logging fails
        console.log(`[AUDIT] Export generated by ${options.professionalName} for ${options.patientName} (${options.format}/${options.recipientType})`);
    }
};

export const generateWhatsAppText = (patientName: string, reportSummary: string, link?: string) => {
    const timeOfDay = new Date().getHours() < 12 ? 'Bom dia' : 'Boa tarde';
    return `${timeOfDay}, ${patientName}.

Aqui é da FisioFlow. Segue o resumo da sua avaliação biomecânica:

"${reportSummary}"

${link ? `Acesse o relatório completo aqui: ${link}` : 'O relatório completo em PDF foi enviado em anexo.'}

Qualquer dúvida, estamos à disposição.
Atenciosamente,
FisioFlow`;
};

export const generateDoctorLetterText = (patientName: string, professionalName: string, findings: string[], evolution: string) => {
    return `Prezado(a) Colega,

Encaminho relatório de avaliação biomecânica do paciente ${patientName}.

RESUMO FUNCIONAL:
Observou-se ${evolution.toLowerCase()}.

ACHADOS RELEVANTES:
${findings.map(f => `- ${f}`).join('\n')}

Seguimos à disposição para discussão do caso.

Atenciosamente,
${professionalName}
Fisioterapeuta`;
};
