[mcp_servers.neon]
enabled = true
type = "http"
url = "https://mcp.neon.tech/mcp"

[mcp_servers.exa]
url = "https://mcp.exa.ai/mcp"

[mcp_servers.shadcn]
enabled = false
command = "npx"
args = ["shadcn@latest", "mcp", "-c", "/home/rafael/Documents/fisioflow/fisioflow-51658291"]
startup_timeout_sec = 30

[mcp_servers.github]
url = "https://server.smithery.ai/smithery-ai/github/mcp"

[mcp_servers.cloudflare-api]
enabled = true
type = "http"
url = "https://mcp.cloudflare.com/mcp"

[mcp_servers.cloudflare-api.tools.search]
approval_mode = "approve"

[mcp_servers.cloudflare-api.tools.execute]
approval_mode = "approve"

[mcp_servers.context7]
type = "http"
url = "https://mcp.context7.com/mcp"

[mcp_servers.context7.http_headers]
"CONTEXT7_API_KEY" = "ctx7sk-ad94ba7f-5d88-47b6-9c00-a478dd2b5343"

[mcp_servers.playwright]
enabled = false
command = "npx"
args = ["-y", "@playwright/mcp@latest"]

[mcp_servers.react-native-mcp]
enabled = false
command = "npx"
args = ["-y", "@ohah/react-native-mcp-server"]

[mcp_servers.chrome-devtools]
enabled = false
command = "npx"
args = ["-y", "chrome-devtools-mcp@latest"]
