# FisioFlow - Cloud Build Pipeline para Cloud Functions
# Free Tier: 2.500 minutos de build/mês
# Otimizado para builds rápidos de Cloud Functions

steps:
  # =========================================================================
  # STEP 1: Setup
  # =========================================================================
  - id: 'setup'
    name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== FisioFlow Functions Build ==="
        echo "Branch: $BRANCH_NAME"
        echo "Commit: $SHORT_SHA"

        # Install pnpm
        npm install -g pnpm@latest

        # Install dependencies with frozen lockfile for reproducibility
        cd functions
        pnpm install --frozen-lockfile --prefer-offline
    waitFor: ['-']

  # =========================================================================
  # STEP 2: Type Checking
  # =========================================================================
  - id: 'typecheck'
    name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd functions
        echo "=== Running Type Check ==="
        pnpm exec tsc --noEmit
    waitFor: ['setup']

  # =========================================================================
  # STEP 3: Linting
  # =========================================================================
  - id: 'lint'
    name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd functions
        echo "=== Running Lint ==="
        pnpm run lint || echo "Linting completed with warnings"
    waitFor: ['setup']

  # =========================================================================
  # STEP 4: Build
  # =========================================================================
  - id: 'build'
    name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd functions
        echo "=== Building Functions ==="
        NODE_OPTIONS='--max-old-space-size=4096' \
        pnpm run build

        # Verificar tamanho do build
        echo "Build output size:"
        du -sh lib/
        du -sh lib/src/

        # Listar funções principais
        echo "Main functions:"
        ls -lh lib/src/index.js 2>/dev/null || echo "index.js not in expected location"
    waitFor: ['typecheck']

  # =========================================================================
  # STEP 5: Unit Tests
  # =========================================================================
  - id: 'test'
    name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd functions
        echo "=== Running Tests ==="
        # Se houver testes configurados
        if [ -f "package.json" ] && grep -q '"test"' package.json; then
          pnpm test || echo "Tests completed"
        else
          echo "No tests configured"
        fi
    waitFor: ['setup']

  # =========================================================================
  # STEP 6: Deploy (Only on main branch or explicit trigger)
  # =========================================================================
  - id: 'deploy'
    name: 'node:22'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Deploying Functions ==="

        # Install Firebase CLI
        npm install -g firebase-tools

        # Deploy functions
        if [ "$BRANCH_NAME" = "main" ] || [ "$_DEPLOY_FUNCTIONS" = "true" ]; then
          firebase deploy --only functions --non-interactive
        else
          echo "Skipping deploy on non-main branch (set _DEPLOY_FUNCTIONS=true to force)"
        fi
    waitFor: ['build']
    env:
      - 'FIREBASE_TOKEN=$_FIREBASE_TOKEN'

timeout: '1200s'  # 20 minutos

logsBucket: 'gs://fisioflow-build-logs'

substitutions:
  _FIREBASE_TOKEN: ''
  _DEPLOY_FUNCTIONS: 'false'
