CREATE INDEX "idx_appointments_organization_id" ON "appointments" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_appointments_patient_id" ON "appointments" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "idx_appointments_therapist_date" ON "appointments" USING btree ("therapist_id","date");--> statement-breakpoint
CREATE INDEX "idx_appointments_status" ON "appointments" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_appointments_room_id" ON "appointments" USING btree ("room_id");--> statement-breakpoint
CREATE INDEX "idx_blocked_slots_organization_id" ON "blocked_slots" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_blocked_slots_therapist_date" ON "blocked_slots" USING btree ("therapist_id","date");--> statement-breakpoint
CREATE INDEX "idx_blocked_slots_room_date" ON "blocked_slots" USING btree ("room_id","date");--> statement-breakpoint
CREATE INDEX "idx_rooms_organization_id" ON "rooms" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_rooms_is_active" ON "rooms" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_exercise_categories_slug" ON "exercise_categories" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "idx_exercise_categories_parent_id" ON "exercise_categories" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "idx_exercise_favorites_exercise_id" ON "exercise_favorites" USING btree ("exercise_id");--> statement-breakpoint
CREATE INDEX "idx_exercise_favorites_user_id" ON "exercise_favorites" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_exercise_favorites_organization_id" ON "exercise_favorites" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_exercises_slug" ON "exercises" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "idx_exercises_category_id" ON "exercises" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "idx_exercises_organization_id" ON "exercises" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_exercises_is_active" ON "exercises" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_goals_medical_record_id" ON "goals" USING btree ("medical_record_id");--> statement-breakpoint
CREATE INDEX "idx_goals_status" ON "goals" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_medical_records_patient_id" ON "medical_records" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "idx_pathologies_medical_record_id" ON "pathologies" USING btree ("medical_record_id");--> statement-breakpoint
CREATE INDEX "idx_pathologies_status" ON "pathologies" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_patient_packages_patient_id" ON "patient_packages" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "idx_patient_packages_status" ON "patient_packages" USING btree ("status");--> statement-breakpoint
CREATE INDEX "idx_patients_organization_id" ON "patients" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_patients_cpf" ON "patients" USING btree ("cpf");--> statement-breakpoint
CREATE INDEX "idx_patients_is_active" ON "patients" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "idx_patients_full_name" ON "patients" USING btree ("full_name");--> statement-breakpoint
CREATE INDEX "idx_surgeries_medical_record_id" ON "surgeries" USING btree ("medical_record_id");--> statement-breakpoint
CREATE INDEX "idx_session_attachments_session_id" ON "session_attachments" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "idx_session_attachments_patient_id" ON "session_attachments" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "idx_session_templates_organization_id" ON "session_templates" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_session_templates_therapist_id" ON "session_templates" USING btree ("therapist_id");--> statement-breakpoint
CREATE INDEX "idx_sessions_patient_id" ON "sessions" USING btree ("patient_id");--> statement-breakpoint
CREATE INDEX "idx_sessions_appointment_id" ON "sessions" USING btree ("appointment_id");--> statement-breakpoint
CREATE INDEX "idx_sessions_therapist_id" ON "sessions" USING btree ("therapist_id");--> statement-breakpoint
CREATE INDEX "idx_sessions_organization_id" ON "sessions" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_sessions_date" ON "sessions" USING btree ("date");--> statement-breakpoint
CREATE INDEX "idx_exercise_protocols_slug" ON "exercise_protocols" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "idx_exercise_protocols_organization_id" ON "exercise_protocols" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_exercise_protocols_protocol_type" ON "exercise_protocols" USING btree ("protocol_type");--> statement-breakpoint
CREATE INDEX "idx_protocol_exercises_protocol_id" ON "protocol_exercises" USING btree ("protocol_id");--> statement-breakpoint
CREATE INDEX "idx_protocol_exercises_exercise_id" ON "protocol_exercises" USING btree ("exercise_id");