name = "r2-presigned-url-worker"
main = "r2-presigned-url-worker.ts"
compatibility_date = "2026-03-25"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "fisioflow-exams"

[[d1_databases]]
binding = "DB"
database_name = "fisioflow-db"
database_id = "bf781be2-527d-471d-9cf2-dd18f8e6c2b2"

[vars]
AUTH_TOKEN = "FISIOFLOW_SECRET_TOKEN_2026"
R2_PUBLIC_URL = "https://r2-worker.rafalegollas.workers.dev"
