-- Rollback for 0080_fix_schema_mismatches.sql
-- Drops columns and compatibility tables added by the hotfix migration.

DROP TABLE IF EXISTS rate_limits;
DROP TABLE IF EXISTS patient_achievements;
DROP TABLE IF EXISTS patient_exercise_logs;
DROP TABLE IF EXISTS patient_portal_users;
DROP TABLE IF EXISTS card_patient_mappings;
DROP TABLE IF EXISTS digital_twin_snapshots;
DROP TABLE IF EXISTS ai_peer_reviews;
DROP TABLE IF EXISTS pre_registrations;
DROP TABLE IF EXISTS pre_registration_tokens;

ALTER TABLE wa_automation_rules DROP COLUMN IF EXISTS team;
ALTER TABLE wa_conversation_tags DROP COLUMN IF EXISTS organization_id;
ALTER TABLE achievements DROP COLUMN IF EXISTS updated_at;
ALTER TABLE treatment_cycles DROP COLUMN IF EXISTS report_url;
ALTER TABLE patient_gamification DROP COLUMN IF EXISTS total_badges;
ALTER TABLE recibos DROP COLUMN IF EXISTS whatsapp_sent_at;
ALTER TABLE group_checkins DROP COLUMN IF EXISTS status;
ALTER TABLE group_checkins DROP COLUMN IF EXISTS session_date;
ALTER TABLE group_checkins DROP COLUMN IF EXISTS enrollment_id;
ALTER TABLE group_enrollments DROP COLUMN IF EXISTS status;
ALTER TABLE group_classes DROP COLUMN IF EXISTS capacity;
ALTER TABLE group_classes DROP COLUMN IF EXISTS end_time;
ALTER TABLE group_classes DROP COLUMN IF EXISTS start_time;
ALTER TABLE group_classes DROP COLUMN IF EXISTS day_of_week;
ALTER TABLE referral_codes DROP COLUMN IF EXISTS expires_at;
ALTER TABLE referral_codes DROP COLUMN IF EXISTS reward_value;
ALTER TABLE referral_codes DROP COLUMN IF EXISTS reward_type;
ALTER TABLE document_signatures DROP COLUMN IF EXISTS signing_token_expires_at;
ALTER TABLE document_signatures DROP COLUMN IF EXISTS signing_token;
ALTER TABLE satisfaction_surveys DROP COLUMN IF EXISTS ai_urgency_alert;
ALTER TABLE satisfaction_surveys DROP COLUMN IF EXISTS ai_summary;
ALTER TABLE satisfaction_surveys DROP COLUMN IF EXISTS ai_sentiment;
ALTER TABLE google_drive_items DROP COLUMN IF EXISTS updated_at;
ALTER TABLE google_drive_items DROP COLUMN IF EXISTS metadata;
ALTER TABLE google_drive_items DROP COLUMN IF EXISTS provider_item_id;
ALTER TABLE google_drive_items DROP COLUMN IF EXISTS integration_id;
ALTER TABLE google_drive_items DROP COLUMN IF EXISTS organization_id;
ALTER TABLE medical_requests DROP COLUMN IF EXISTS status;
ALTER TABLE medical_requests DROP COLUMN IF EXISTS specialty;
ALTER TABLE medical_requests DROP COLUMN IF EXISTS requested_by;
ALTER TABLE medical_requests DROP COLUMN IF EXISTS mime_type;
ALTER TABLE medical_requests DROP COLUMN IF EXISTS file_size;
ALTER TABLE medical_requests DROP COLUMN IF EXISTS file_name;
ALTER TABLE medical_requests DROP COLUMN IF EXISTS r2_key;
ALTER TABLE medical_requests DROP COLUMN IF EXISTS title;
ALTER TABLE medical_requests DROP COLUMN IF EXISTS request_type;
ALTER TABLE medical_requests DROP COLUMN IF EXISTS professional_id;
ALTER TABLE patient_packages DROP COLUMN IF EXISTS purchase_date;
ALTER TABLE patient_packages DROP COLUMN IF EXISTS financial_record_id;
ALTER TABLE patient_packages DROP COLUMN IF EXISTS notes;
ALTER TABLE patient_packages DROP COLUMN IF EXISTS expiry_date;
ALTER TABLE patient_packages DROP COLUMN IF EXISTS amount_paid;
ALTER TABLE patient_packages DROP COLUMN IF EXISTS package_id;
ALTER TABLE patient_pathologies DROP COLUMN IF EXISTS created_by;
ALTER TABLE patient_pathologies DROP COLUMN IF EXISTS treated_at;
ALTER TABLE patient_pathologies DROP COLUMN IF EXISTS affected_region;
ALTER TABLE patient_pathologies DROP COLUMN IF EXISTS severity;
ALTER TABLE medical_records DROP COLUMN IF EXISTS created_by;
ALTER TABLE medical_records DROP COLUMN IF EXISTS record_date;
ALTER TABLE medical_records DROP COLUMN IF EXISTS lifestyle_habits;
ALTER TABLE medical_records DROP COLUMN IF EXISTS previous_surgeries;
ALTER TABLE medical_records DROP COLUMN IF EXISTS current_medications;
ALTER TABLE medical_records DROP COLUMN IF EXISTS medical_history;
ALTER TABLE medical_records DROP COLUMN IF EXISTS organization_id;
