-- Security layer for the Notes tables generated by Drizzle.
-- Apply this after the matching packages/db migration.

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'notes', 'note_revisions', 'note_permissions', 'note_mentions', 'note_relations',
    'note_comments', 'note_attachments', 'note_tasks', 'note_audit_logs'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', table_name);
    -- The generated Drizzle migration creates the tenant policy. This layer
    -- makes it apply even to the table owner, so every access is org-scoped.
  END LOOP;
END $$;
