// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/welcome": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/pre-cadastro": {
    params: {};
  };
  "/pre-cadastro/:token": {
    params: {
      token: string;
    };
  };
  "/feedback-pre-cadastro": {
    params: {};
  };
  "/pending-approval": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/pacientes": {
    params: {};
  };
  "/patients/new": {
    params: {};
  };
  "/patients/:id": {
    params: {
      id: string;
    };
  };
  "/pacientes/:id/mapas-dor": {
    params: {
      id: string;
    };
  };
  "/patients/:patientId/evaluations/new/:formId?": {
    params: {
      patientId: string;
      formId?: string;
    };
  };
  "/patient-evolution/:appointmentId": {
    params: {
      appointmentId: string;
    };
  };
  "/patient-evolution-report/:patientId": {
    params: {
      patientId: string;
    };
  };
  "/session-evolution/:appointmentId": {
    params: {
      appointmentId: string;
    };
  };
  "/financial": {
    params: {};
  };
  "/financeiro/fluxo-caixa": {
    params: {};
  };
  "/financeiro/contas": {
    params: {};
  };
  "/financeiro/recibos": {
    params: {};
  };
  "/financeiro/nfse": {
    params: {};
  };
  "/schedule": {
    params: {};
  };
  "/schedule/settings": {
    params: {};
  };
  "/exercises": {
    params: {};
  };
  "/protocols": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/organization": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page:
      | "/"
      | "/welcome"
      | "/auth"
      | "/auth/login"
      | "/pre-cadastro"
      | "/pre-cadastro/:token"
      | "/feedback-pre-cadastro"
      | "/pending-approval"
      | "/dashboard"
      | "/pacientes"
      | "/patients/new"
      | "/patients/:id"
      | "/pacientes/:id/mapas-dor"
      | "/patients/:patientId/evaluations/new/:formId?"
      | "/patient-evolution/:appointmentId"
      | "/patient-evolution-report/:patientId"
      | "/session-evolution/:appointmentId"
      | "/financial"
      | "/financeiro/fluxo-caixa"
      | "/financeiro/contas"
      | "/financeiro/recibos"
      | "/financeiro/nfse"
      | "/schedule"
      | "/schedule/settings"
      | "/exercises"
      | "/protocols"
      | "/settings"
      | "/profile"
      | "/organization";
  };
  "components/layout/InfrastructureLayout.tsx": {
    id: "components/layout/InfrastructureLayout";
    page:
      | "/welcome"
      | "/auth"
      | "/auth/login"
      | "/pre-cadastro"
      | "/pre-cadastro/:token"
      | "/feedback-pre-cadastro"
      | "/pending-approval"
      | "/"
      | "/dashboard"
      | "/pacientes"
      | "/patients/new"
      | "/patients/:id"
      | "/pacientes/:id/mapas-dor"
      | "/patients/:patientId/evaluations/new/:formId?"
      | "/patient-evolution/:appointmentId"
      | "/patient-evolution-report/:patientId"
      | "/session-evolution/:appointmentId"
      | "/financial"
      | "/financeiro/fluxo-caixa"
      | "/financeiro/contas"
      | "/financeiro/recibos"
      | "/financeiro/nfse"
      | "/schedule"
      | "/schedule/settings"
      | "/exercises"
      | "/protocols"
      | "/settings"
      | "/profile"
      | "/organization";
  };
  "pages/Welcome.tsx": {
    id: "pages/Welcome";
    page: "/welcome";
  };
  "pages/Auth.tsx":
    | {
        id: "auth-root";
        page: "/auth";
      }
    | {
        id: "auth-login";
        page: "/auth/login";
      };
  "pages/PreCadastro.tsx":
    | {
        id: "pre-cadastro-root";
        page: "/pre-cadastro";
      }
    | {
        id: "pre-cadastro-token";
        page: "/pre-cadastro/:token";
      };
  "pages/FeedbackPreCadastro.tsx": {
    id: "pages/FeedbackPreCadastro";
    page: "/feedback-pre-cadastro";
  };
  "pages/PendingApproval.tsx": {
    id: "pages/PendingApproval";
    page: "/pending-approval";
  };
  "components/layout/AppShellLayout.tsx": {
    id: "components/layout/AppShellLayout";
    page:
      | "/"
      | "/dashboard"
      | "/pacientes"
      | "/patients/new"
      | "/patients/:id"
      | "/pacientes/:id/mapas-dor"
      | "/patients/:patientId/evaluations/new/:formId?"
      | "/patient-evolution/:appointmentId"
      | "/patient-evolution-report/:patientId"
      | "/session-evolution/:appointmentId"
      | "/financial"
      | "/financeiro/fluxo-caixa"
      | "/financeiro/contas"
      | "/financeiro/recibos"
      | "/financeiro/nfse"
      | "/schedule"
      | "/schedule/settings"
      | "/exercises"
      | "/protocols"
      | "/settings"
      | "/profile"
      | "/organization";
  };
  "pages/Index.tsx": {
    id: "pages/Index";
    page: "/";
  };
  "pages/SmartDashboard.tsx": {
    id: "pages/SmartDashboard";
    page: "/dashboard";
  };
  "pages/Patients.tsx": {
    id: "pages/Patients";
    page: "/pacientes";
  };
  "pages/patients/NewPatientPage.tsx": {
    id: "pages/patients/NewPatientPage";
    page: "/patients/new";
  };
  "pages/patients/PatientProfilePage.tsx": {
    id: "pages/patients/PatientProfilePage";
    page: "/patients/:id";
  };
  "pages/patients/PainMapHistoryPage.tsx": {
    id: "pages/patients/PainMapHistoryPage";
    page: "/pacientes/:id/mapas-dor";
  };
  "pages/patients/NewEvaluationPage.tsx": {
    id: "pages/patients/NewEvaluationPage";
    page: "/patients/:patientId/evaluations/new/:formId?";
  };
  "pages/PatientEvolution.tsx": {
    id: "pages/PatientEvolution";
    page: "/patient-evolution/:appointmentId";
  };
  "pages/PatientEvolutionReport.tsx": {
    id: "pages/PatientEvolutionReport";
    page: "/patient-evolution-report/:patientId";
  };
  "pages/SessionEvolutionPage.tsx": {
    id: "pages/SessionEvolutionPage";
    page: "/session-evolution/:appointmentId";
  };
  "pages/Financial.tsx": {
    id: "pages/Financial";
    page: "/financial";
  };
  "pages/financeiro/FluxoCaixaPage.tsx": {
    id: "pages/financeiro/FluxoCaixaPage";
    page: "/financeiro/fluxo-caixa";
  };
  "pages/financeiro/ContasFinanceirasPage.tsx": {
    id: "pages/financeiro/ContasFinanceirasPage";
    page: "/financeiro/contas";
  };
  "pages/financeiro/RecibosPage.tsx": {
    id: "pages/financeiro/RecibosPage";
    page: "/financeiro/recibos";
  };
  "pages/financeiro/NFSePage.tsx": {
    id: "pages/financeiro/NFSePage";
    page: "/financeiro/nfse";
  };
  "pages/Schedule.tsx": {
    id: "pages/Schedule";
    page: "/schedule";
  };
  "pages/ScheduleSettings.tsx": {
    id: "pages/ScheduleSettings";
    page: "/schedule/settings";
  };
  "pages/Exercises.tsx": {
    id: "pages/Exercises";
    page: "/exercises";
  };
  "pages/Protocols.tsx": {
    id: "pages/Protocols";
    page: "/protocols";
  };
  "pages/Settings.tsx": {
    id: "pages/Settings";
    page: "/settings";
  };
  "pages/Profile.tsx": {
    id: "pages/Profile";
    page: "/profile";
  };
  "pages/OrganizationSettings.tsx": {
    id: "pages/OrganizationSettings";
    page: "/organization";
  };
};

type RouteModules = {
  root: typeof import("./../../src/root.tsx");
  "components/layout/InfrastructureLayout": typeof import("./../../src/components/layout/InfrastructureLayout.tsx");
  "pages/Welcome": typeof import("./../../src/pages/Welcome.tsx");
  "auth-root": typeof import("./../../src/pages/Auth.tsx");
  "auth-login": typeof import("./../../src/pages/Auth.tsx");
  "pre-cadastro-root": typeof import("./../../src/pages/PreCadastro.tsx");
  "pre-cadastro-token": typeof import("./../../src/pages/PreCadastro.tsx");
  "pages/FeedbackPreCadastro": typeof import("./../../src/pages/FeedbackPreCadastro.tsx");
  "pages/PendingApproval": typeof import("./../../src/pages/PendingApproval.tsx");
  "components/layout/AppShellLayout": typeof import("./../../src/components/layout/AppShellLayout.tsx");
  "pages/Index": typeof import("./../../src/pages/Index.tsx");
  "pages/SmartDashboard": typeof import("./../../src/pages/SmartDashboard.tsx");
  "pages/Patients": typeof import("./../../src/pages/Patients.tsx");
  "pages/patients/NewPatientPage": typeof import("./../../src/pages/patients/NewPatientPage.tsx");
  "pages/patients/PatientProfilePage": typeof import("./../../src/pages/patients/PatientProfilePage.tsx");
  "pages/patients/PainMapHistoryPage": typeof import("./../../src/pages/patients/PainMapHistoryPage.tsx");
  "pages/patients/NewEvaluationPage": typeof import("./../../src/pages/patients/NewEvaluationPage.tsx");
  "pages/PatientEvolution": typeof import("./../../src/pages/PatientEvolution.tsx");
  "pages/PatientEvolutionReport": typeof import("./../../src/pages/PatientEvolutionReport.tsx");
  "pages/SessionEvolutionPage": typeof import("./../../src/pages/SessionEvolutionPage.tsx");
  "pages/Financial": typeof import("./../../src/pages/Financial.tsx");
  "pages/financeiro/FluxoCaixaPage": typeof import("./../../src/pages/financeiro/FluxoCaixaPage.tsx");
  "pages/financeiro/ContasFinanceirasPage": typeof import("./../../src/pages/financeiro/ContasFinanceirasPage.tsx");
  "pages/financeiro/RecibosPage": typeof import("./../../src/pages/financeiro/RecibosPage.tsx");
  "pages/financeiro/NFSePage": typeof import("./../../src/pages/financeiro/NFSePage.tsx");
  "pages/Schedule": typeof import("./../../src/pages/Schedule.tsx");
  "pages/ScheduleSettings": typeof import("./../../src/pages/ScheduleSettings.tsx");
  "pages/Exercises": typeof import("./../../src/pages/Exercises.tsx");
  "pages/Protocols": typeof import("./../../src/pages/Protocols.tsx");
  "pages/Settings": typeof import("./../../src/pages/Settings.tsx");
  "pages/Profile": typeof import("./../../src/pages/Profile.tsx");
  "pages/OrganizationSettings": typeof import("./../../src/pages/OrganizationSettings.tsx");
};
