/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/exercises` | `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/financial` | `/financial`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/patients` | `/patients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/exercises` | `/exercises`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/financial` | `/financial`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/patients` | `/patients`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/exercises${`?${string}` | `#${string}` | ''}` | `/exercises${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/financial${`?${string}` | `#${string}` | ''}` | `/financial${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/patients${`?${string}` | `#${string}` | ''}` | `/patients${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/exercises` | `/exercises`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/financial` | `/financial`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/patients` | `/patients`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
