export const app = null;
export const auth = null;
export const db = null;
export const storage = null;
export const functions = null;
export const remoteConfig = null;

export const getFirebaseApp = () => null;
export const getFirebaseAuth = () => null;
export const getFirestoreDb = () => null;
export const getFirebaseStorage = () => null;
export const getFirebaseFunctions = () => null;
export const getRemoteValue = () => null;

export const doc = (..._args: unknown[]) => null;
export const getDoc = async (..._args: unknown[]) => ({ exists: () => false, data: () => null, id: '' });
export const setDoc = async (..._args: unknown[]) => undefined;
export const updateDoc = async (..._args: unknown[]) => undefined;
export const collection = (..._args: unknown[]) => null;
export const collectionGroup = (..._args: unknown[]) => null;
export const getDocs = async (..._args: unknown[]) => ({ docs: [], empty: true });
export const query = (..._args: unknown[]) => null;
export const where = (..._args: unknown[]) => null;
export const limit = (..._args: unknown[]) => null;
export const addDoc = async (..._args: unknown[]) => ({ id: '' });
export const deleteDoc = async (..._args: unknown[]) => undefined;
export const orderBy = (..._args: unknown[]) => null;
export const onSnapshot = (..._args: unknown[]) => () => undefined;
export const getDocsFromCache = async (..._args: unknown[]) => ({ docs: [], empty: true });
export const getDocFromCache = async (..._args: unknown[]) => ({ exists: () => false, data: () => null, id: '' });
export const getDocsFromServer = async (..._args: unknown[]) => ({ docs: [], empty: true });
export const getDocFromServer = async (..._args: unknown[]) => ({ exists: () => false, data: () => null, id: '' });
export const getCountFromServer = async (..._args: unknown[]) => ({ data: () => ({ count: 0 }) });
export const Timestamp = { now: () => ({ toDate: () => new Date() }) };
export const serverTimestamp = () => new Date().toISOString();
export const increment = (value: number) => value;
export const arrayUnion = (...values: unknown[]) => values;
export const arrayRemove = (...values: unknown[]) => values;
export const deleteField = () => undefined;
export const runTransaction = async (..._args: unknown[]) => undefined;
export const writeBatch = () => ({ set: () => undefined, update: () => undefined, delete: () => undefined, commit: async () => undefined });
export const startAfter = (..._args: unknown[]) => null;
export const startAt = (..._args: unknown[]) => null;
export const endBefore = (..._args: unknown[]) => null;
export const endAt = (..._args: unknown[]) => null;
export const and = (..._args: unknown[]) => null;
export const or = (..._args: unknown[]) => null;
export const documentId = () => '__document_id__';
export const httpsCallable = () => async () => ({ data: null });
export const cleanForFirestore = <T>(value: T) => value;

export type Firestore = null;
export type Query<T = unknown> = T;
export type CollectionReference<T = unknown> = T;
export type DocumentReference<T = unknown> = T;
export type DocumentData = Record<string, unknown>;
export type QueryDocumentSnapshot<T = DocumentData> = { id: string; data: () => T };
export type QuerySnapshot<T = DocumentData> = { docs: QueryDocumentSnapshot<T>[]; empty: boolean };
export type QueryConstraint = unknown;
export type Unsubscribe = () => void;
