import {
  pgTable,
  uuid,
  text,
  timestamp,
  numeric,
  jsonb,
  integer,
  index,
  date,
} from "drizzle-orm/pg-core";
import { organizations } from "./organizations";
import { withOrganizationPolicy } from "./rls_helper";

/**
 * Business Metrics - Finance & Strategy (BI)
 * Stores pre-calculated or snapshotted metrics for the Smart Dashboard.
 */
export const businessMetrics = pgTable(
  "business_metrics",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id")
      .references(() => organizations.id)
      .notNull(),
    
    metricDate: date("metric_date").notNull(), // Snapshot date (e.g., daily or monthly)
    
    // Financial KPIs
    totalRevenue: numeric("total_revenue", { precision: 12, scale: 2 }).default("0"),
    cacEstimated: numeric("cac_estimated", { precision: 12, scale: 2 }), // Marketing Spend / New Patients
    ltvEstimated: numeric("ltv_estimated", { precision: 12, scale: 2 }), // Avg Revenue * Lifespan
    paybackMonths: numeric("payback_months", { precision: 5, scale: 2 }),
    
    // Growth KPIs
    newPatientsCount: integer("new_patients_count").default(0),
    churnRate: numeric("churn_rate", { precision: 5, scale: 2 }), // % of patients not returning
    activePatients: integer("active_patients").default(0),
    
    // Insights
    aiInsights: text("ai_insights"), // Summary generated by AI about these numbers
    metadata: jsonb("metadata").default({}),
    
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    index("idx_business_metrics_org_date").on(table.organizationId, table.metricDate),
    withOrganizationPolicy("business_metrics", table.organizationId),
  ]
);

/**
 * Predictive Adherence Tracking
 * Stores predictions about patient behavior to prevent drop-outs.
 */
export const patientAdherencePredictions = pgTable(
  "patient_adherence_predictions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    organizationId: uuid("organization_id").notNull(),
    patientId: uuid("patient_id").notNull(),
    
    predictionDate: timestamp("prediction_date").defaultNow().notNull(),
    
    // Scores (0-100)
    adherenceScore: integer("adherence_score"), // Probability of completing treatment
    dropoutRisk: integer("dropout_risk"), // Risk of churn (0-100)
    
    // Factors
    riskFactors: jsonb("risk_factors").$type<string[]>(), // e.g., ["low session frequency", "high pain report"]
    suggestedAction: text("suggested_action"), // AI suggestion: "Call patient", "Send reminder"
    
    status: text("status", { enum: ["active", "addressed", "resolved"] }).default("active"),
    
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("idx_adherence_patient").on(table.patientId),
    withOrganizationPolicy("patient_adherence_predictions", table.organizationId),
  ]
);
