export const APP_ROUTES = {
  HOME: "/",
  DASHBOARD: "/dashboard",
  SMART_DASHBOARD: "/smart-dashboard",
  AGENDA: "/agenda",
  PATIENTS: "/patients",
  PATIENT_NEW: "/patients/new",
  EXERCISES: "/exercises",
  FINANCIAL: "/financial",
  REPORTS: "/reports",
  SETTINGS: "/profile",
  EVENTS: "/eventos",
  TASKS: "/tarefas",
  IA_STUDIO: "/inteligencia?tab=studio",
  INTELLIGENCE: "/inteligencia",
  CRM: "/crm",
  CRM_PIPELINE: "/crm/pipeline",
  CRM_INBOX: "/crm/inbox",
  CRM_TASKS: "/crm/tasks",
  CRM_AUTOMATIONS: "/crm/automations",
  CRM_ANALYTICS: "/crm/analytics",
  CRM_CAMPAIGNS: "/crm/campaigns",
} as const;

export const patientRoutes = {
  profile: (patientId: string) => `${APP_ROUTES.PATIENTS}/${patientId}`,
  clinicalTab: (patientId: string) => `${APP_ROUTES.PATIENTS}/${patientId}?tab=clinical`,
  overviewTab: (patientId: string) => `${APP_ROUTES.PATIENTS}/${patientId}?tab=overview`,
  documentsTab: (patientId: string) => `${APP_ROUTES.PATIENTS}/${patientId}?tab=documents`,
  evaluation: (patientId: string) => `${APP_ROUTES.PATIENTS}/${patientId}/evaluation`,
  evolution: (patientId: string) => `${APP_ROUTES.PATIENTS}/${patientId}/evolution`,
} as const;
