import type { StandardFormsMap } from "./types";

export const STANDARD_FORMS: StandardFormsMap = {
  ANAMNESE: {
    nome: "Anamnese Completa",
    tipo: "anamnese",
    descricao: "Ficha de anamnese completa para fisioterapia",
    campos: [
      // Dados pessoais
      {
        rotulo: "Nome Completo",
        pergunta: "Qual o nome completo do paciente?",
        tipo_campo: "texto_curto",
        secao: "Dados Pessoais",
        ordem: 1,
        obrigatorio: true,
      },
      {
        rotulo: "Data de Nascimento",
        pergunta: "Data de nascimento",
        tipo_campo: "data",
        secao: "Dados Pessoais",
        ordem: 2,
        obrigatorio: true,
      },
      {
        rotulo: "Ocupação",
        pergunta: "Qual a ocupação profissional?",
        tipo_campo: "texto_curto",
        secao: "Dados Pessoais",
        ordem: 3,
        obrigatorio: false,
      },
      {
        rotulo: "Telefone",
        pergunta: "Telefone para contato",
        tipo_campo: "texto_curto",
        secao: "Dados Pessoais",
        ordem: 4,
        obrigatorio: true,
      },
      // Queixa e Histórico
      {
        rotulo: "Queixa Principal",
        pergunta: "Qual o motivo principal da consulta?",
        tipo_campo: "texto_longo",
        secao: "Queixa e Histórico",
        ordem: 5,
        obrigatorio: true,
      },
      {
        rotulo: "Início do Problema",
        pergunta: "Quando o problema começou?",
        tipo_campo: "texto_curto",
        secao: "Queixa e Histórico",
        ordem: 6,
        obrigatorio: true,
      },
      {
        rotulo: "Histórico da Doença Atual",
        pergunta: "Descreva como a doença evoluiu até hoje",
        tipo_campo: "texto_longo",
        secao: "Queixa e Histórico",
        ordem: 7,
        obrigatorio: false,
      },
      {
        rotulo: "Dor",
        pergunta: "Qual a intensidade da dor (0-10)?",
        tipo_campo: "escala",
        secao: "Queixa e Histórico",
        ordem: 8,
        obrigatorio: true,
        minimo: 0,
        maximo: 10,
        opcoes: ["Sem dor", "Dor máxima"],
      },
      // Histórico Médico
      {
        rotulo: "Doenças Preexistentes",
        pergunta: "Possui alguma doença preexistente? (diabetes, hipertensão, etc.)",
        tipo_campo: "texto_longo",
        secao: "Histórico Médico",
        ordem: 9,
        obrigatorio: false,
      },
      {
        rotulo: "Cirurgias Prévias",
        pergunta: "Já realizou alguma cirurgia? Quais?",
        tipo_campo: "texto_longo",
        secao: "Histórico Médico",
        ordem: 10,
        obrigatorio: false,
      },
      {
        rotulo: "Medicamentos em Uso",
        pergunta: "Toma algum medicamento atualmente? Quais?",
        tipo_campo: "texto_longo",
        secao: "Histórico Médico",
        ordem: 11,
        obrigatorio: false,
      },
      {
        rotulo: "Alergias",
        pergunta: "Possui alguma alergia a medicamentos ou alimentos?",
        tipo_campo: "texto_longo",
        secao: "Histórico Médico",
        ordem: 12,
        obrigatorio: true,
      },
      // Histórico Familiar
      {
        rotulo: "Histórico Familiar",
        pergunta: "Algum familiar com problemas semelhantes?",
        tipo_campo: "texto_longo",
        secao: "Histórico Familiar",
        ordem: 13,
        obrigatorio: false,
      },
      // Hábitos de Vida
      {
        rotulo: "Prática de Atividade Física",
        pergunta: "Pratica alguma atividade física regularmente?",
        tipo_campo: "radio",
        secao: "Hábitos de Vida",
        ordem: 14,
        obrigatorio: false,
        opcoes: ["Sim", "Não", "Anteriormente"],
      },
      {
        rotulo: "Frequência da Atividade",
        pergunta: "Quantas vezes por semana?",
        tipo_campo: "texto_curto",
        secao: "Hábitos de Vida",
        ordem: 15,
        obrigatorio: false,
      },
      {
        rotulo: "Tabagismo",
        pergunta: "É fumante?",
        tipo_campo: "radio",
        secao: "Hábitos de Vida",
        ordem: 16,
        obrigatorio: false,
        opcoes: ["Sim", "Não", "Ex-fumante"],
      },
      {
        rotulo: "Consumo de Álcool",
        pergunta: "Consome bebidas alcoólicas?",
        tipo_campo: "radio",
        secao: "Hábitos de Vida",
        ordem: 17,
        obrigatorio: false,
        opcoes: ["Não", "Socialmente", "Diariamente"],
      },
      // Outros
      {
        rotulo: "Observações Adicionais",
        pergunta: "Alguma outra informação relevante?",
        tipo_campo: "texto_longo",
        secao: "Outros",
        ordem: 18,
        obrigatorio: false,
      },
    ],
  },
  AVALIACAO_POSTURAL: {
    nome: "Avaliação Postural",
    tipo: "avaliacao_postural",
    descricao: "Ficha de avaliação postural completa",
    campos: [
      // Vista Anterior
      {
        rotulo: "Cabeça - Vista Anterior",
        pergunta: "Observações sobre a posição da cabeça (vista anterior)",
        tipo_campo: "texto_longo",
        secao: "Vista Anterior",
        ordem: 1,
        obrigatorio: false,
        descricao: "Inclinações laterais, rotações, assimetrias",
      },
      {
        rotulo: "Ombros - Vista Anterior",
        pergunta: "Observações sobre os ombros (vista anterior)",
        tipo_campo: "texto_longo",
        secao: "Vista Anterior",
        ordem: 2,
        obrigatorio: false,
        descricao: "Nivelamento, elevação, protração, assimetrias",
      },
      {
        rotulo: "Escápulas - Vista Anterior",
        pergunta: "Observações sobre as escápulas (vista anterior)",
        tipo_campo: "texto_longo",
        secao: "Vista Anterior",
        ordem: 3,
        obrigatorio: false,
        descricao: "Alada, aderida, assimetrias",
      },
      {
        rotulo: "Pelve - Vista Anterior",
        pergunta: "Observações sobre a pelve (vista anterior)",
        tipo_campo: "texto_longo",
        secao: "Vista Anterior",
        ordem: 4,
        obrigatorio: false,
        descricao: "Nivelamento, inclinações, rotações",
      },
      {
        rotulo: "Joelhos - Vista Anterior",
        pergunta: "Observações sobre os joelhos (vista anterior)",
        tipo_campo: "texto_longo",
        secao: "Vista Anterior",
        ordem: 5,
        obrigatorio: false,
        descricao: "Varo, valgo, simetria",
      },
      {
        rotulo: "Pés - Vista Anterior",
        pergunta: "Observações sobre os pés (vista anterior)",
        tipo_campo: "texto_longo",
        secao: "Vista Anterior",
        ordem: 6,
        obrigatorio: false,
        descricao: "Plano, cavo, abdução, adução",
      },
      // Vista Posterior
      {
        rotulo: "Coluna Vertebral - Vista Posterior",
        pergunta: "Observações sobre a coluna (vista posterior)",
        tipo_campo: "texto_longo",
        secao: "Vista Posterior",
        ordem: 7,
        obrigatorio: false,
        descricao: "Escolioses, gibosidade, alinhamento",
      },
      {
        rotulo: "Escápulas - Vista Posterior",
        pergunta: "Observações sobre as escápulas (vista posterior)",
        tipo_campo: "texto_longo",
        secao: "Vista Posterior",
        ordem: 8,
        obrigatorio: false,
        descricao: "Alinhamento, simetria, mobilidade",
      },
      {
        rotulo: "Pelve - Vista Posterior",
        pergunta: "Observações sobre a pelve (vista posterior)",
        tipo_campo: "texto_longo",
        secao: "Vista Posterior",
        ordem: 9,
        obrigatorio: false,
        descricao: "Nível, torsão, diferença de altura",
      },
      {
        rotulo: "Tornozelos - Vista Posterior",
        pergunta: "Observações sobre os tornozelos (vista posterior)",
        tipo_campo: "texto_longo",
        secao: "Vista Posterior",
        ordem: 10,
        obrigatorio: false,
        descricao: "Valgo, varo, diferença de altura",
      },
      // Vista Lateral
      {
        rotulo: "Cabeça - Vista Lateral",
        pergunta: "Observações sobre a cabeça (vista lateral)",
        tipo_campo: "texto_longo",
        secao: "Vista Lateral",
        ordem: 11,
        obrigatorio: false,
        descricao: "Posição anteriorizada, posteriorizada, rotação",
      },
      {
        rotulo: "Cervical - Vista Lateral",
        pergunta: "Observações sobre a região cervical (vista lateral)",
        tipo_campo: "texto_longo",
        secao: "Vista Lateral",
        ordem: 12,
        obrigatorio: false,
        descricao: "Lordose, retificação, protração de cabeça",
      },
      {
        rotulo: "Ombros - Vista Lateral",
        pergunta: "Observações sobre os ombros (vista lateral)",
        tipo_campo: "texto_longo",
        secao: "Vista Lateral",
        ordem: 13,
        obrigatorio: false,
        descricao: "Protração, arredondamento",
      },
      {
        rotulo: "Torax - Vista Lateral",
        pergunta: "Observações sobre o tórax (vista lateral)",
        tipo_campo: "texto_longo",
        secao: "Vista Lateral",
        ordem: 14,
        obrigatorio: false,
        descricao: "Cifose, retificação, simetria",
      },
      {
        rotulo: "Lombar - Vista Lateral",
        pergunta: "Observações sobre a região lombar (vista lateral)",
        tipo_campo: "texto_longo",
        secao: "Vista Lateral",
        ordem: 15,
        obrigatorio: false,
        descricao: "Lordose, retificação, flexão",
      },
      {
        rotulo: "Pelve - Vista Lateral",
        pergunta: "Observações sobre a pelve (vista lateral)",
        tipo_campo: "texto_longo",
        secao: "Vista Lateral",
        ordem: 16,
        obrigatorio: false,
        descricao: "Anterversão, retroversão, nível",
      },
      // Testes Específicos
      {
        rotulo: "Teste de Nash",
        pergunta: "Resultado do teste de Nash (triângulo de Sorensen)",
        tipo_campo: "dropdown",
        secao: "Testes Específicos",
        ordem: 17,
        obrigatorio: false,
        opcoes: ["Normal", "Alterado à direita", "Alterado à esquerda", "Não realizado"],
      },
      {
        rotulo: "Teste de Adams",
        pergunta: "Resultado do teste de Adams para escoliose",
        tipo_campo: "dropdown",
        secao: "Testes Específicos",
        ordem: 18,
        obrigatorio: false,
        opcoes: ["Negativo", "Positivo à direita", "Positivo à esquerda", "Não realizado"],
      },
      // Mapa Corporal
      {
        rotulo: "Mapa de Dor",
        pergunta: "Indique as áreas de dor no corpo",
        tipo_campo: "mapa_corporal",
        secao: "Mapa Corporal",
        ordem: 19,
        obrigatorio: false,
      },
      // Conclusão
      {
        rotulo: "Diagnóstico Postural",
        pergunta: "Diagnóstico postural geral",
        tipo_campo: "texto_longo",
        secao: "Conclusão",
        ordem: 20,
        obrigatorio: true,
      },
      {
        rotulo: "Conduta Sugerida",
        pergunta: "Conduta terapêutica sugerida",
        tipo_campo: "texto_longo",
        secao: "Conclusão",
        ordem: 21,
        obrigatorio: true,
      },
    ],
  },
  AVALIACAO_FUNCIONAL: {
    nome: "Avaliação Funcional",
    tipo: "avaliacao_funcional",
    descricao: "Ficha de avaliação funcional e testes físicos",
    campos: [
      // Amplitude de Movimento
      {
        rotulo: "ADM - Cervical",
        pergunta: "Amplitude de movimento cervical (flexão, extensão, rotações, inclinações)",
        tipo_campo: "texto_longo",
        secao: "Amplitude de Movimento (ADM)",
        ordem: 1,
        obrigatorio: false,
        descricao: "Descreva os graus de movimento encontrados",
      },
      {
        rotulo: "ADM - Ombros",
        pergunta: "Amplitude de movimento dos ombros",
        tipo_campo: "texto_longo",
        secao: "Amplitude de Movimento (ADM)",
        ordem: 2,
        obrigatorio: false,
      },
      {
        rotulo: "ADM - Cotovelos",
        pergunta: "Amplitude de movimento dos cotovelos",
        tipo_campo: "texto_longo",
        secao: "Amplitude de Movimento (ADM)",
        ordem: 3,
        obrigatorio: false,
      },
      {
        rotulo: "ADM - Punhos",
        pergunta: "Amplitude de movimento dos punhos",
        tipo_campo: "texto_longo",
        secao: "Amplitude de Movimento (ADM)",
        ordem: 4,
        obrigatorio: false,
      },
      {
        rotulo: "ADM - Coluna Torácica",
        pergunta: "Amplitude de movimento da coluna torácica",
        tipo_campo: "texto_longo",
        secao: "Amplitude de Movimento (ADM)",
        ordem: 5,
        obrigatorio: false,
      },
      {
        rotulo: "ADM - Coluna Lombar",
        pergunta: "Amplitude de movimento da coluna lombar",
        tipo_campo: "texto_longo",
        secao: "Amplitude de Movimento (ADM)",
        ordem: 6,
        obrigatorio: false,
      },
      {
        rotulo: "ADM - Quadris",
        pergunta: "Amplitude de movimento dos quadris",
        tipo_campo: "texto_longo",
        secao: "Amplitude de Movimento (ADM)",
        ordem: 7,
        obrigatorio: false,
      },
      {
        rotulo: "ADM - Joelhos",
        pergunta: "Amplitude de movimento dos joelhos",
        tipo_campo: "texto_longo",
        secao: "Amplitude de Movimento (ADM)",
        ordem: 8,
        obrigatorio: false,
      },
      {
        rotulo: "ADM - Tornozelos",
        pergunta: "Amplitude de movimento dos tornozelos",
        tipo_campo: "texto_longo",
        secao: "Amplitude de Movimento (ADM)",
        ordem: 9,
        obrigatorio: false,
      },
      // Força Muscular
      {
        rotulo: "Força - Cintura Escapular",
        pergunta: "Testes de força da cintura escapular",
        tipo_campo: "texto_longo",
        secao: "Força Muscular",
        ordem: 10,
        obrigatorio: false,
        descricao: "Use escala de Oxford/LOF (0-5)",
      },
      {
        rotulo: "Força - Cintura Pélvica",
        pergunta: "Testes de força da cintura pélvica",
        tipo_campo: "texto_longo",
        secao: "Força Muscular",
        ordem: 11,
        obrigatorio: false,
      },
      {
        rotulo: "Força - Membros Superiores",
        pergunta: "Testes de força dos membros superiores",
        tipo_campo: "texto_longo",
        secao: "Força Muscular",
        ordem: 12,
        obrigatorio: false,
      },
      {
        rotulo: "Força - Membros Inferiores",
        pergunta: "Testes de força dos membros inferiores",
        tipo_campo: "texto_longo",
        secao: "Força Muscular",
        ordem: 13,
        obrigatorio: false,
      },
      // Reflexos
      {
        rotulo: "Reflexos - Bicipital",
        pergunta: "Reflexo bicipital",
        tipo_campo: "dropdown",
        secao: "Reflexos",
        ordem: 14,
        obrigatorio: false,
        opcoes: ["Normal (2+)", "Hipo reflexia (0-1+)", "Hiper reflexia (3-4+)", "Ausente"],
      },
      {
        rotulo: "Reflexos - Tricipital",
        pergunta: "Reflexo tricipital",
        tipo_campo: "dropdown",
        secao: "Reflexos",
        ordem: 15,
        obrigatorio: false,
        opcoes: ["Normal (2+)", "Hipo reflexia (0-1+)", "Hiper reflexia (3-4+)", "Ausente"],
      },
      {
        rotulo: "Reflexos - Patelar",
        pergunta: "Reflexo patelar",
        tipo_campo: "dropdown",
        secao: "Reflexos",
        ordem: 16,
        obrigatorio: false,
        opcoes: ["Normal (2+)", "Hipo reflexia (0-1+)", "Hiper reflexia (3-4+)", "Ausente"],
      },
      {
        rotulo: "Reflexos - Aquileu",
        pergunta: "Reflexo aquileu",
        tipo_campo: "dropdown",
        secao: "Reflexos",
        ordem: 17,
        obrigatorio: false,
        opcoes: ["Normal (2+)", "Hipo reflexia (0-1+)", "Hiper reflexia (3-4+)", "Ausente"],
      },
      // Testes Especiais
      {
        rotulo: "Testes Especiais",
        pergunta: "Testes ortopédicos especiais realizados",
        tipo_campo: "texto_longo",
        secao: "Testes Especiais",
        ordem: 18,
        obrigatorio: false,
        descricao: "Ex: Lasegue, slump, Yergason, Speed, etc.",
      },
      // Sensibilidade
      {
        rotulo: "Sensibilidade - Superficial",
        pergunta: "Teste de sensibilidade superficial (tato, dor, temperatura)",
        tipo_campo: "texto_longo",
        secao: "Sensibilidade",
        ordem: 19,
        obrigatorio: false,
      },
      {
        rotulo: "Sensibilidade - Profunda",
        pergunta: "Teste de sensibilidade profunda (vibração, propriocepção)",
        tipo_campo: "texto_longo",
        secao: "Sensibilidade",
        ordem: 20,
        obrigatorio: false,
      },
      // Testes Funcionais
      {
        rotulo: "Marcha",
        pergunta: "Avaliação da marcha",
        tipo_campo: "texto_longo",
        secao: "Testes Funcionais",
        ordem: 21,
        obrigatorio: false,
      },
      {
        rotulo: "Equilíbrio",
        pergunta: "Testes de equilíbrio (Romberg, tandem, etc.)",
        tipo_campo: "texto_longo",
        secao: "Testes Funcionais",
        ordem: 22,
        obrigatorio: false,
      },
      {
        rotulo: "Coordenação",
        pergunta: "Testes de coordenação (dedo-nariz, calcanhar-joelho)",
        tipo_campo: "texto_longo",
        secao: "Testes Funcionais",
        ordem: 23,
        obrigatorio: false,
      },
      // Conclusão
      {
        rotulo: "Diagnóstico Funcional",
        pergunta: "Diagnóstico funcional do paciente",
        tipo_campo: "texto_longo",
        secao: "Conclusão",
        ordem: 24,
        obrigatorio: true,
      },
      {
        rotulo: "Prognóstico",
        pergunta: "Prognóstico estimado",
        tipo_campo: "texto_longo",
        secao: "Conclusão",
        ordem: 25,
        obrigatorio: true,
      },
    ],
  },
  FISIOTERAPIA_ORTOPEDICA: {
    nome: "Avaliação Ortopédica Avançada",
    tipo: "ortopedica",
    descricao: "Avaliação detalhada para disfunções musculoesqueléticas e traumato-ortopédicas",
    campos: [
      {
        rotulo: "Mecanismo de Lesão",
        pergunta: "Descreva como e quando ocorreu a lesão ou início dos sintomas",
        tipo_campo: "texto_longo",
        secao: "Anamnese Específica",
        ordem: 1,
        obrigatorio: true,
      },
      {
        rotulo: "Fatores de Melhora e Piora",
        pergunta: "O que alivia e o que intensifica os sintomas?",
        tipo_campo: "texto_longo",
        secao: "Anamnese Específica",
        ordem: 2,
        obrigatorio: false,
      },
      {
        rotulo: "Comportamento da Dor",
        pergunta: "A dor é constante ou intermitente? Piora em algum período do dia?",
        tipo_campo: "texto_longo",
        secao: "Anamnese Específica",
        ordem: 3,
        obrigatorio: false,
      },
      {
        rotulo: "Amplitude de Movimento Ativa",
        pergunta: "ADM Ativa (em graus ou descrição)",
        tipo_campo: "texto_longo",
        secao: "Exame Físico Ortopédico",
        ordem: 4,
        obrigatorio: false,
      },
      {
        rotulo: "Amplitude de Movimento Passiva",
        pergunta: "ADM Passiva e Sensação de Fim de Curso (End-feel)",
        tipo_campo: "texto_longo",
        secao: "Exame Físico Ortopédico",
        ordem: 5,
        obrigatorio: false,
      },
      {
        rotulo: "Testes de Força (Oxford)",
        pergunta: "Grau de força muscular (0-5)",
        tipo_campo: "texto_longo",
        secao: "Exame Físico Ortopédico",
        ordem: 6,
        obrigatorio: false,
      },
      {
        rotulo: "Testes Especiais Ortopédicos",
        pergunta: "Resultados de testes específicos (Ex: Lachman, Drawer, Hawkins, etc.)",
        tipo_campo: "texto_longo",
        secao: "Testes Específicos",
        ordem: 7,
        obrigatorio: false,
      },
      {
        rotulo: "Palpação e Tecidos Moles",
        pergunta: "Pontos gatilho, edema, temperatura, sensibilidade local",
        tipo_campo: "texto_longo",
        secao: "Testes Específicos",
        ordem: 8,
        obrigatorio: false,
      },
      {
        rotulo: "Escala Funcional (Oswestry/DASH/LEFS)",
        pergunta: "Pontuação na escala funcional aplicada",
        tipo_campo: "texto_curto",
        secao: "Avaliação Funcional",
        ordem: 9,
        obrigatorio: false,
      },
      {
        rotulo: "Diagnóstico e Conduta",
        pergunta: "Diagnóstico cinético-funcional e plano de tratamento",
        tipo_campo: "texto_longo",
        secao: "Conclusão",
        ordem: 10,
        obrigatorio: true,
      },
    ],
  },
  FISIOTERAPIA_ESPORTIVA: {
    nome: "Avaliação para Fisioterapia Esportiva",
    tipo: "esportiva",
    descricao: "Modelo focado em atletas, retorno ao esporte e performance funcional",
    campos: [
      {
        rotulo: "Modalidade Esportiva",
        pergunta: "Qual esporte pratica? Qual posição/função?",
        tipo_campo: "texto_curto",
        secao: "Perfil do Atleta",
        ordem: 1,
        obrigatorio: true,
      },
      {
        rotulo: "Nível de Competição",
        pergunta: "Amador, Profissional, Elite?",
        tipo_campo: "dropdown",
        secao: "Perfil do Atleta",
        ordem: 2,
        obrigatorio: false,
        opcoes: ["Amador", "Recreativo", "Profissional", "Alto Rendimento"],
      },
      {
        rotulo: "Volume de Treino",
        pergunta: "Frequência semanal e horas por dia",
        tipo_campo: "texto_curto",
        secao: "Perfil do Atleta",
        ordem: 3,
        obrigatorio: false,
      },
      {
        rotulo: "Avaliação Biomecânica Dinâmica",
        pergunta: "Observações de movimento (Squat, Lunge, Salto)",
        tipo_campo: "texto_longo",
        secao: "Análise de Movimento",
        ordem: 4,
        obrigatorio: false,
      },
      {
        rotulo: "Y-Balance Test / Star Excursion",
        pergunta: "Resultados de equilíbrio dinâmico",
        tipo_campo: "texto_curto",
        secao: "Testes de Performance",
        ordem: 5,
        obrigatorio: false,
      },
      {
        rotulo: "Hop Tests (Saltos Unipodais)",
        pergunta: "Distância e simetria (LSI - Limb Symmetry Index)",
        tipo_campo: "texto_curto",
        secao: "Testes de Performance",
        ordem: 6,
        obrigatorio: false,
      },
      {
        rotulo: "Prontidão Psicológica (ACL-RSI)",
        pergunta: "Escala de confiança para retorno ao esporte",
        tipo_campo: "escala",
        secao: "Retorno ao Esporte",
        ordem: 7,
        obrigatorio: false,
        minimo: 0,
        maximo: 100,
      },
      {
        rotulo: "Critérios para Return to Play",
        pergunta: "O atleta cumpre os critérios para progressão de carga/retorno?",
        tipo_campo: "texto_longo",
        secao: "Retorno ao Esporte",
        ordem: 8,
        obrigatorio: true,
      },
    ],
  },
  FISIOTERAPIA_POS_OPERATORIA: {
    nome: "Protocolo de Avaliação Pós-Operatória",
    tipo: "padrao",
    descricao: "Acompanhamento de reabilitação cirúrgica, fases de cicatrização e cuidados",
    campos: [
      {
        rotulo: "Data da Cirurgia",
        pergunta: "Quando a cirurgia foi realizada?",
        tipo_campo: "data",
        secao: "Dados Cirúrgicos",
        ordem: 1,
        obrigatorio: true,
      },
      {
        rotulo: "Procedimento Realizado",
        pergunta: "Qual o diagnóstico e a técnica cirúrgica utilizada?",
        tipo_campo: "texto_longo",
        secao: "Dados Cirúrgicos",
        ordem: 2,
        obrigatorio: true,
      },
      {
        rotulo: "Cirurgião Responsável",
        pergunta: "Nome do médico e equipe",
        tipo_campo: "texto_curto",
        secao: "Dados Cirúrgicos",
        ordem: 3,
        obrigatorio: false,
      },
      {
        rotulo: "Avaliação da Ferida Operatória",
        pergunta: "Estado dos pontos, presença de secreção, sinais inflamatórios",
        tipo_campo: "texto_longo",
        secao: "Exame Clínico Pós-Op",
        ordem: 4,
        obrigatorio: true,
      },
      {
        rotulo: "Controle de Edema e Derrame",
        pergunta: "Perimetria ou graduação do edema",
        tipo_campo: "texto_curto",
        secao: "Exame Clínico Pós-Op",
        ordem: 5,
        obrigatorio: false,
      },
      {
        rotulo: "Precauções e Restrições",
        pergunta: "Limites de carga, ADM permitida, uso de órteses/muletas",
        tipo_campo: "texto_longo",
        secao: "Orientações e Limites",
        ordem: 6,
        obrigatorio: true,
      },
      {
        rotulo: "Fase de Reabilitação Atual",
        pergunta: "Em qual fase do protocolo o paciente se encontra?",
        tipo_campo: "dropdown",
        secao: "Evolução",
        ordem: 7,
        obrigatorio: true,
        opcoes: [
          "Fase I: Proteção Máxima",
          "Fase II: Proteção Moderada",
          "Fase III: Retorno Funcional",
          "Fase IV: Performance",
        ],
      },
      {
        rotulo: "Metas para Próxima Fase",
        pergunta: "O que falta para progredir?",
        tipo_campo: "texto_longo",
        secao: "Evolução",
        ordem: 8,
        obrigatorio: false,
      },
    ],
  },
};
