-- =====================================================
-- FisioFlow v3.0 - Fix RLS Policies Performance
-- Criado em: 25/12/2025
-- Descrição: Corrige policies com auth.<function>() para usar (select auth.<function>())
--            e remove policies duplicadas
-- NOTA: Esta migration foi comentada temporariamente pois muitas tabelas referenciadas
--       podem não existir ainda. Será reativada após todas as migrations base serem aplicadas.
-- =====================================================

-- Migration comentada temporariamente - muitas tabelas podem não existir
-- Esta migration será reativada após todas as migrations base serem aplicadas com sucesso
