-- Enable Supabase Vector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- ========================================
-- Add vector columns to exercises table
-- ========================================

ALTER TABLE exercises
ADD COLUMN IF NOT EXISTS embedding vector(1536);

-- Create HNSW index for fast similarity search
CREATE INDEX IF NOT EXISTS exercises_embedding_idx
ON exercises
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- ========================================
-- Add vector columns to protocols table
-- ========================================

ALTER TABLE exercise_protocols
ADD COLUMN IF NOT EXISTS embedding vector(1536);

CREATE INDEX IF NOT EXISTS exercise_protocols_embedding_idx
ON exercise_protocols
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- ========================================
-- Add vector columns to patients table (for clinical similarity)
-- ========================================

ALTER TABLE patients
ADD COLUMN IF NOT EXISTS clinical_history_embedding vector(1536);

CREATE INDEX IF NOT EXISTS patients_clinical_embedding_idx
ON patients
USING hnsw (clinical_history_embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- ========================================
-- Add vector columns to medical_records table
-- ========================================

ALTER TABLE medical_records
ADD COLUMN IF NOT EXISTS embedding vector(1536);

CREATE INDEX IF NOT EXISTS medical_records_embedding_idx
ON medical_records
USING hnsw (embedding vector_cosine_ops)
WITH (m = 16, ef_construction = 64);

-- ========================================
-- Create function to update exercise embedding
-- ========================================

CREATE OR REPLACE FUNCTION update_exercise_embedding()
RETURNS TRIGGER AS $$
BEGIN
  -- This function is called when an exercise is created/updated
  -- The actual embedding should be generated by the application
  -- using OpenAI's embedding API
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ========================================
-- Create trigger for exercises
-- ========================================

DROP TRIGGER IF EXISTS exercise_embedding_trigger ON exercises;

CREATE TRIGGER exercise_embedding_trigger
BEFORE INSERT OR UPDATE ON exercises
FOR EACH ROW
EXECUTE FUNCTION update_exercise_embedding();

-- ========================================
-- Create function for semantic search
-- ========================================

CREATE OR REPLACE FUNCTION search_exercises_semantic(
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.75,
  match_count int DEFAULT 10,
  organization_id_param uuid DEFAULT NULL
)
RETURNS TABLE (
  id uuid,
  name text,
  description text,
  category text,
  difficulty text,
  similarity float
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    e.id,
    e.name,
    e.description,
    e.category,
    e.difficulty,
    1 - (e.embedding <=> query_embedding) as similarity
  FROM exercises e
  WHERE
    e.embedding IS NOT NULL AND
    (organization_id_param IS NULL OR e.organization_id = organization_id_param) AND
    (1 - (e.embedding <=> query_embedding)) > match_threshold
  ORDER BY e.embedding <=> query_embedding
  LIMIT match_count;
END;
$$ LANGUAGE plpgsql;

-- ========================================
-- Create function for protocol semantic search
-- ========================================

CREATE OR REPLACE FUNCTION search_protocols_semantic(
  query_embedding vector(1536),
  match_threshold float DEFAULT 0.75,
  match_count int DEFAULT 10,
  organization_id_param uuid DEFAULT NULL
)
RETURNS TABLE (
  id uuid,
  name text,
  description text,
  category text,
  duration_weeks int,
  similarity float
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id,
    p.name,
    p.description,
    p.category,
    p.duration_weeks,
    1 - (p.embedding <=> query_embedding) as similarity
  FROM exercise_protocols p
  WHERE
    p.embedding IS NOT NULL AND
    (organization_id_param IS NULL OR p.organization_id = organization_id_param) AND
    (1 - (p.embedding <=> query_embedding)) > match_threshold
  ORDER BY p.embedding <=> query_embedding
  LIMIT match_count;
END;
$$ LANGUAGE plpgsql;

-- ========================================
-- Create function for similar patients search
-- ========================================

CREATE OR REPLACE FUNCTION find_similar_patients(
  clinical_embedding vector(1536),
  match_threshold float DEFAULT 0.8,
  match_count int DEFAULT 5,
  organization_id_param uuid DEFAULT NULL
)
RETURNS TABLE (
  id uuid,
  name text,
  age int,
  primary_diagnosis text,
  similarity float
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    p.id,
    p.name,
    EXTRACT(YEAR FROM AGE(p.date_of_birth))::int as age,
    p.primary_diagnosis,
    1 - (p.clinical_history_embedding <=> clinical_embedding) as similarity
  FROM patients p
  WHERE
    p.clinical_history_embedding IS NOT NULL AND
    (organization_id_param IS NULL OR p.organization_id = organization_id_param) AND
    (1 - (p.clinical_history_embedding <=> clinical_embedding)) > match_threshold
  ORDER BY p.clinical_history_embedding <=> clinical_embedding
  LIMIT match_count;
END;
$$ LANGUAGE plpgsql;

-- ========================================
-- Add comment for documentation
-- ========================================

COMMENT ON COLUMN exercises.embedding IS 'Vector embedding for semantic search (1536 dimensions for OpenAI text-embedding-3-small)';
COMMENT ON COLUMN exercise_protocols.embedding IS 'Vector embedding for semantic search (1536 dimensions for OpenAI text-embedding-3-small)';
COMMENT ON COLUMN patients.clinical_history_embedding IS 'Vector embedding of clinical history for patient similarity matching';
COMMENT ON COLUMN medical_records.embedding IS 'Vector embedding for clinical record semantic search';

-- ========================================
-- Grant necessary permissions
-- ========================================

-- These permissions are typically already set by RLS policies
-- But we'll add explicit grants for the vector functions

GRANT EXECUTE ON FUNCTION search_exercises_semantic TO authenticated;
GRANT EXECUTE ON FUNCTION search_protocols_semantic TO authenticated;
GRANT EXECUTE ON FUNCTION find_similar_patients TO authenticated;
