-- Seed Clinical Tests Library (PhysioTests Pro)
-- Cleans up existing templates to avoid duplicates (re-runnable)
DELETE FROM clinical_test_templates WHERE organization_id IS NULL;

INSERT INTO clinical_test_templates (name, category, target_joint, purpose, execution, positive_sign, sensitivity_specificity, reference, tags, type, fields_definition) VALUES

-- ORTOPEDIA --
(
    'Teste de Neer',
    'Ortopedia',
    'Ombro',
    'Avaliar conflito subacromial e compressão do manguito rotador',
    'Paciente em pé ou sentado. O examinador estabiliza a escápula com uma mão e eleva passivamente o membro superior do paciente no plano da escápula, com rotação interna, até o limite da amplitude. A elevação é realizada com o polegar apontando para baixo.',
    'Dor na região anterossuperior do ombro quando o braço é elevado entre 70° e 120°',
    'Sensibilidade 68-91%, Especificidade 30-74%',
    'Neer CS, 1972',
    ARRAY['Ortopedia', 'neer test', 'shoulder impingement', 'subacromial conflict'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Hawkins-Kennedy',
    'Ortopedia',
    'Ombro',
    'Avaliar conflito subacromial com o tendão supraespinhal',
    'Paciente em pé ou sentado. O examinador flexiona o ombro a 90° e o cotovelo a 90°, mantendo o braço na horizontal. Realiza rotação interna passiva do ombro, aproximando o antebraço do corpo.',
    'Dor na região anterossuperior do ombro durante a rotação interna',
    'Sensibilidade 62-92%, Especificidade 25-66%',
    'Hawkins RJ, Kennedy JC, 1980',
    ARRAY['Ortopedia', 'hawkins kennedy test', 'shoulder impingement', 'rotator cuff'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Jobe (Empty Can)',
    'Ortopedia',
    'Ombro',
    'Avaliar a integridade e força do músculo supraespinhal',
    'Paciente em pé com o ombro em 90° de abdução, 30° de flexão horizontal e rotação interna máxima (polegares apontando para baixo). O examinador aplica resistência na direção de abdução enquanto o paciente tenta manter a posição.',
    'Dor ou fraqueza na região deltoide anterior, incapacidade de manter a posição contra resistência',
    'Sensibilidade 86-88%, Especificidade 50-70%',
    'Jobe FW, Moynes DR, 1982',
    ARRAY['Ortopedia', 'jobe test', 'empty can test', 'supraspinatus', 'shoulder strength'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste Full Can',
    'Ortopedia',
    'Ombro',
    'Avaliar a integridade do supraespinhal com menor provocação de dor que o Empty Can',
    'Paciente em pé com o ombro em 90° de abdução, 30° de flexão horizontal e rotação externa neutra (polegares apontando para cima). O examinador aplica resistência na direção de abdução enquanto o paciente tenta manter a posição.',
    'Dor ou fraqueza na região deltoide anterior durante a resistência',
    'Sensibilidade 75-84%, Especificidade 58-75%',
    'Itoi E et al., 1999',
    ARRAY['Ortopedia', 'full can test', 'supraspinatus', 'shoulder examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Speed',
    'Ortopedia',
    'Ombro',
    'Avaliar tendinopatia do bíceps braquial (porção longa)',
    'Paciente em pé com o cotovelo estendido, antebraço supinado e ombro flexionado a 60-90°. O examinador aplica resistência na direção de flexão do ombro enquanto o paciente tenta manter a posição.',
    'Dor na região bicipital (sulco intertubercular) durante a resistência',
    'Sensibilidade 32-68%, Especificidade 55-75%',
    'Bennett WF, 1998',
    ARRAY['Ortopedia', 'speed test', 'biceps tendon', 'shoulder pain'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Yergason',
    'Ortopedia',
    'Ombro',
    'Avaliar a estabilidade do tendão longo do bíceps no sulco bicipital',
    'Paciente sentado ou em pé com o cotovelo flexionado a 90° e antebraço pronado. O examinador segura o punho do paciente e aplica resistência à supinação enquanto o paciente tenta supinar o antebraço.',
    'Dor na região bicipital ou subluxação do tendão do bíceps do sulco',
    'Sensibilidade 43-93%, Especificidade 13-79%',
    'Yergason RM, 1931',
    ARRAY['Ortopedia', 'yergason test', 'biceps tendon', 'sulco bicipital'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de O''Brien (SLAP Test)',
    'Ortopedia',
    'Ombro',
    'Avaliar lesões SLAP (Superior Labrum Anterior to Posterior)',
    'Paciente em pé com o ombro flexionado a 90°, aduzido 10-15° e em rotação interna (polegar apontando para baixo). O examinador aplica resistência na direção de flexão. Repete o teste com o antebraço supinado.',
    'Dor profunda no ombro na primeira posição (rotação interna) que diminui na segunda posição (supinação)',
    'Sensibilidade 47-100%, Especificidade 56-98%',
    'O''Brien SJ et al., 1998',
    ARRAY['Ortopedia', 'obrien test', 'slap lesion', 'labrum', 'shoulder examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Apprehension',
    'Ortopedia',
    'Ombro',
    'Avaliar instabilidade anterior do ombro',
    'Paciente em decúbito dorsal com o ombro abduzido a 90° e cotovelo flexionado a 90°. O examinador aplica pressão anteriormente na cabeça do úmero, promovendo translação anterior.',
    'Sensação de luxação iminente, apreensão ou espasmo muscular defensivo',
    'Sensibilidade 46-98%, Especificidade 48-100%',
    'Rowe CR, Zarins B, 1981',
    ARRAY['Ortopedia', 'apprehension test', 'shoulder instability', 'anterior translation'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Relocation (Jobe)',
    'Ortopedia',
    'Ombro',
    'Confirmar instabilidade anterior do ombro',
    'Realizado após o teste de apprehension. Com o paciente na mesma posição, o examinador aplica pressão posterior na cabeça do úmero enquanto o braço é mantido em abdução e rotação externa.',
    'Diminuição ou desaparecimento da sensação de apreensão e dor relatada no teste de apprehension',
    'Sensibilidade 44-88%, Especificidade 50-93%',
    'Jobe FW et al., 1989',
    ARRAY['Ortopedia', 'relocation test', 'shoulder instability', 'jobe relocation'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Drop Arm',
    'Ortopedia',
    'Ombro',
    'Avaliar ruptura completa do manguito rotador',
    'Paciente em pé ou sentado. O examinador eleva passivamente o ombro do paciente até 90° de abdução ou até o limite de dor. Solicita-se ao paciente manter a posição e depois abaixar lentamente o braço.',
    'Incapacidade de manter a posição ou queda súbita do braço durante a descida controlada',
    'Sensibilidade 10-73%, Especificidade 81-98%',
    'Codman EA, 1934',
    ARRAY['Ortopedia', 'drop arm test', 'rotator cuff tear', 'shoulder examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Lift-off',
    'Ortopedia',
    'Ombro',
    'Avaliar a integridade do músculo subescapular',
    'Paciente sentado com a mão na região lombar, cotovelo flexionado e ombro em extensão e rotação interna. Solicita-se ao paciente afastar a mão da lombar contra resistência do examinador.',
    'Incapacidade de realizar o movimento ou fraqueza significativa comparada ao lado contralateral',
    'Sensibilidade 22-60%, Especificidade 85-100%',
    'Gerber C, Krushell RJ, 1991',
    ARRAY['Ortopedia', 'lift off test', 'subscapularis', 'shoulder internal rotation'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Belly Press',
    'Ortopedia',
    'Ombro',
    'Avaliar a integridade do músculo subescapular',
    'Paciente em pé ou sentado com o cotovelo flexionado a 90° e ombro em rotação interna. O paciente pressiona a barriga com a palma da mão enquanto o examinador tenta puxar o antebraço para frente.',
    'Incapacidade de manter o cotovelo posterior ao plano do corpo ou compensação com extensão do ombro',
    'Sensibilidade 40-75%, Especificidade 92-98%',
    'Gerber C et al., 1996',
    ARRAY['Ortopedia', 'belly press test', 'subscapularis', 'shoulder examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste Bear Hug',
    'Ortopedia',
    'Ombro',
    'Avaliar lesão do subescapular em sua porção superior e média',
    'Paciente coloca a mão do lado afetado sobre o ombro oposto, com os dedos estendidos sobre a clavícula. O examinador tenta puxar a mão para frente enquanto o paciente resiste mantendo a posição.',
    'Fraqueza ou incapacidade de manter a mão no ombro oposto contra resistência moderada',
    'Sensibilidade 60-75%, Especificidade 92-95%',
    'Barth JRH et al., 2006',
    ARRAY['Ortopedia', 'bear hug test', 'subscapularis', 'shoulder internal rotation'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Lachman',
    'Ortopedia',
    'Joelho',
    'Avaliar a integridade do ligamento cruzado anterior (LCA)',
    'Paciente em decúbito dorsal com o joelho fletido a 20-30°. O examinador estabiliza o fêmur com uma mão e com a outra traciona a tíbia anteriormente, mantendo a mão proximal ao maléolo medial.',
    'Movimento de translação anterior da tíbia em relação ao fêmur com ponto final macio ou ausente',
    'Sensibilidade 87-93%, Especificidade 93-95%',
    'Torg JS et al., 1976',
    ARRAY['Ortopedia', 'lachman test', 'acl tear', 'knee examination', 'anterior cruciate ligament'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste da Gaveta Anterior',
    'Ortopedia',
    'Joelho',
    'Avaliar a integridade do ligamento cruzado anterior (LCA)',
    'Paciente em decúbito dorsal com o joelho fletido a 90° e o pé apoiado na mesa. O examinador senta sobre o pé do paciente e com ambas as mãos traciona a tíbia anteriormente, com os dedos nos hamstrings para garantir relaxamento.',
    'Deslocamento anterior da tíbia em relação ao fêmur, classificado em grau I, II ou III',
    'Sensibilidade 22-95%, Especificidade 78-99%',
    'Feagin JA, Curl WW, 1976',
    ARRAY['Ortopedia', 'anterior drawer test', 'acl tear', 'knee instability'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste da Gaveta Posterior',
    'Ortopedia',
    'Joelho',
    'Avaliar a integridade do ligamento cruzado posterior (LCP)',
    'Paciente em decúbito dorsal com o joelho fletido a 90° e o pé apoiado na mesa. O examinador senta sobre o pé do paciente e com ambas as mãos empurra a tíbia posteriormente enquanto observa se há deslocamento anormal.',
    'Deslocamento posterior da tíbia em relação ao fêmur em graus variáveis',
    'Sensibilidade 80-98%, Especificidade 93-99%',
    'Godfrey D, 1976',
    ARRAY['Ortopedia', 'posterior drawer test', 'pcl tear', 'knee instability'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Pivot Shift',
    'Ortopedia',
    'Joelho',
    'Avaliar instabilidade dinâmica do joelho em rotatória anterior',
    'Paciente em decúbito dorsal com flexão máxima do joelho. O examinador coloca uma mão na face lateral do joelho e a outra no tornozelo. Realiza extensão lenta do joelho enquanto aplica pressão em varo e rotação interna da tíbia.',
    'Sensação de deslocamento anterior da tíbia seguido de redução com clique ou pop palpável',
    'Sensibilidade 32-98%, Especificidade 95-98%',
    'MacIntosh DL, 1972',
    ARRAY['Ortopedia', 'pivot shift test', 'acl tear', 'rotatory instability', 'knee examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Valgo Stress (0°)',
    'Ortopedia',
    'Joelho',
    'Avaliar a integridade do ligamento colateral medial',
    'Paciente em decúbito dorsal com o joelho em extensão total. O examinador coloca uma mão na face medial do joelho próxima à articulação e a outra segura o tornozelo, aplicando estresse em valgo (abrindo o joelho).',
    'Abertura da articulação na face medial do joelho, indicando dano ao LCM',
    'Sensibilidade 70-90%, Especificidade 85-95%',
    'Fukuda T et al., 2000',
    ARRAY['Ortopedia', 'valgus stress test', 'mcl tear', 'knee examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Valgo Stress (30°)',
    'Ortopedia',
    'Joelho',
    'Avaliar a integridade do ligamento colateral medial e cápsula posterior',
    'Paciente em decúbito dorsal com o joelho fletido a 30°. O examinador coloca uma mão na face medial do joelho próxima à articulação e a outra segura o tornozelo, aplicando estresse em valgo.',
    'Abertura da articulação na face medial do joelho quando fletido a 30°',
    'Sensibilidade 73-98%, Especificidade 89-99%',
    'Fukuda T et al., 2000',
    ARRAY['Ortopedia', 'valgus stress test', 'mcl tear', 'knee examination', '30 degrees'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Varo Stress (0°)',
    'Ortopedia',
    'Joelho',
    'Avaliar a integridade do ligamento colateral lateral',
    'Paciente em decúbito dorsal com o joelho em extensão total. O examinador coloca uma mão na face lateral do joelho próxima à articulação e a outra segura o tornozelo, aplicando estresse em varo (fechando o joelho).',
    'Abertura da articulação na face lateral do joelho',
    'Sensibilidade 70-90%, Especificidade 85-95%',
    'Fukuda T et al., 2000',
    ARRAY['Ortopedia', 'varus stress test', 'lcl tear', 'knee examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de McMurray',
    'Ortopedia',
    'Joelho',
    'Avaliar dano ao menisco medial ou lateral',
    'Paciente em decúbito dorsal com o joelho fletido ao máximo. O examinador coloca uma mão no calcanhar e a outra sobre a articulação do joelho. Realiza extensão do joelho com rotação interna (lesão medial) ou externa (lesão lateral) da tíbia.',
    'Clique ou pop palpável ou audível durante o movimento de extensão com rotação',
    'Sensibilidade 16-98%, Especificidade 58-98%',
    'McMurray TP, 1942',
    ARRAY['Ortopedia', 'mcmurray test', 'meniscus tear', 'knee examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Apley',
    'Ortopedia',
    'Joelho',
    'Avaliar dano ao menisco',
    'Paciente em decúbito ventral com o joelho fletido a 90°. O examinador comprime o joelho enquanto realiza rotação interna e externa da tíbia.',
    'Dor ou clique durante a compressão combinada com rotação',
    'Sensibilidade 10-60%, Especificidade 65-85%',
    'Apley AG, 1947',
    ARRAY['Ortopedia', 'apley test', 'meniscus tear', 'knee examination', 'prone position'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Thessaly',
    'Ortopedia',
    'Joelho',
    'Avaliar dano ao menisco com alta sensibilidade',
    'Paciente em pé com o joelho fletido a 20° e 5° de rotação interna da tíbia. O examinador segura as mãos do paciente enquanto o paciente realiza movimento de rotação da tíbia em relação ao fêmur fixo.',
    'Dor medial ou lateral do joelho durante o movimento ou bloqueio do joelho',
    'Sensibilidade 86-94%, Especificidade 88-95%',
    'Karachalios T et al., 2005',
    ARRAY['Ortopedia', 'thessaly test', 'meniscus tear', 'knee examination', 'weight bearing'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Apreensão Patelar',
    'Ortopedia',
    'Joelho',
    'Avaliar instabilidade patelar e dor patellofemoral',
    'Paciente em decúbito dorsal com o joelho estendido. O examinador coloca o polegar sobre a patela e a desloca lateralmente enquanto o paciente relaxa.',
    'Sensação de apreensão ou ansiedade de que a patela possa sair do lugar',
    'Sensibilidade 27-72%, Especificidade 83-100%',
    'Coltman A et al., 2012',
    ARRAY['Ortopedia', 'patellar apprehension test', 'patellofemoral instability', 'knee examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Clarke (Sinal de Clarke)',
    'Ortopedia',
    'Joelho',
    'Avaliar síndrome patellofemoral e dor anterior do joelho',
    'Paciente em decúbito dorsal com o joelho estendido. O examinador coloca a mão acima da patela e aplica pressão distal enquanto o paciente contrai o quadríceps isometricamente.',
    'Dor retropatelar ou anterior durante a contração isométrica do quadríceps',
    'Sensibilidade 22-47%, Especificidade 70-82%',
    'Clarke CR et al., 1974',
    ARRAY['Ortopedia', 'clarke sign', 'patellofemoral pain', 'knee examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Thomas',
    'Ortopedia',
    'Quadril',
    'Avaliar flexão de quadril e encurtamento de flexores',
    'Paciente em decúbito dorsal. O examinador coloca uma mão sob a coluna lombar do paciente e com a outra flexiona o quadril não testado, aproximando o joelho do tórax para neutralizar a lordose.',
    'Elevação da coxa do lado testado, indicando encurtamento dos flexores do quadril',
    'Sensibilidade 85-92%, Especificidade 87-90%',
    'Thomas HO, 1876',
    ARRAY['Ortopedia', 'thomas test', 'hip flexor contracture', 'hip examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de FABER',
    'Ortopedia',
    'Quadril',
    'Avaliar dor na articulação sacroilíaca e/ou na zona anterior do quadril',
    'Paciente em decúbito dorsal. O examinador posiciona o quadril testado em flexão, abdução e rotação externa. Aplica pressão lentamente sobre o joelho testado em direção à maca.',
    'Dor na região inguinal anterior, região lateral do quadril ou sacroilíaca',
    'Sensibilidade 66-88%, Especificidade 65-88%',
    'Cibulka MT et al., 1988',
    ARRAY['Ortopedia', 'faber test', 'hip pain', 'sacroiliac pain', 'hip examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de FADIR',
    'Ortopedia',
    'Quadril',
    'Avaliar dor na articulação do quadril e possível impacto femoroacetabular',
    'Paciente em decúbito dorsal. O examinador posiciona o quadril testado em flexão a 90°, adução e rotação interna. Aplica pressão para aumentar os movimentos.',
    'Dor reproduzida na região inguinal anterior, indicando possível impacto femoroacetabular',
    'Sensibilidade 87-99%, Especificidade 41-77%',
    'Mag JF et al., 2006',
    ARRAY['Ortopedia', 'fadir test', 'femoroacetabular impingement', 'hip pain', 'hip examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Ely',
    'Ortopedia',
    'Quadril',
    'Avaliar encurtamento do músculo reto femoral',
    'Paciente em decúbito dorsal. O examinador flexiona o joelho do lado testado, aproximando o calcanhar à nádega enquanto observa se a coxa se eleva da maca.',
    'Elevação da coxa da maca ou aumento de lordose lombar, indicando encurtamento do reto femoral',
    'Sensibilidade 80-95%, Especificidade 82-92%',
    'Ely LW, 1882',
    ARRAY['Ortopedia', 'ely test', 'rectus femoris', 'hip examination', 'contracture'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Ober',
    'Ortopedia',
    'Quadril',
    'Avaliar encurtamento da banda iliotibial (TFL) e do glúteo máximo',
    'Paciente em decúbito lateral sobre o lado não testado. O examinador abduz e estende levemente o quadril testado, depois deixa cair a coxa passivamente enquanto monitora se a coxa permanece em abdução ou cai.',
    'A coxa permanece em abdução acima da linha média do corpo, indicando encurtamento',
    'Sensibilidade 76-92%, Especificidade 81-93%',
    'Ober FR, 1936',
    ARRAY['Ortopedia', 'ober test', 'iliotibial band', 'hip examination', 'contracture'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Trendelenburg',
    'Ortopedia',
    'Quadril',
    'Avaliar a força do glúteo médio e possível disfunção',
    'Paciente em pé sobre uma perna enquanto a outra coxa é levantada a 90°. O examinador observa se a pelve se inclina para o lado da coxa levantada.',
    'Queda da pelve do lado da coxa levantada, indicando fraqueza do glúteo médio do lado em apoio',
    'Sensibilidade 70-78%, Especificidade 83-92%',
    'Trendelenburg F, 1895',
    ARRAY['Ortopedia', 'trendelenburg test', 'hip abductor weakness', 'gluteus medius', 'hip examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de SLR (Lasegue)',
    'Ortopedia',
    'Coluna',
    'Avaliar radiculopatia lombossacra e extensibilidade dos nervos',
    'Paciente em decúbito dorsal com o quadril a 0° e joelho estendido. O examinador eleva passivamente a perna testada até o aparecimento de dor, mantendo o joelho estendido.',
    'Dor irradiada no trajeto do nervo ciático antes de 70° de elevação, ou limitação severa do movimento',
    'Sensibilidade 72-97%, Especificidade 31-99%',
    'Lasegue JC, 1881',
    ARRAY['Ortopedia', 'slr test', 'straight leg raise', 'sciatica', 'nerve tension', 'lumbar examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Slump',
    'Ortopedia',
    'Coluna',
    'Avaliar tensão neural e radiculopatia com flexão de tronco',
    'Paciente sentado no final da maca. O examinador posiciona o paciente em flexão de tronco (slump), depois estende passivamente o joelho enquanto nota aparecimento de dor ou restrição.',
    'Dor no trajeto do ciático ou limitação da extensão do joelho durante a flexão de tronco',
    'Sensibilidade 69-84%, Especificidade 81-91%',
    'Maitland GD, 1985',
    ARRAY['Ortopedia', 'slump test', 'nerve tension', 'radiculopathy', 'lumbar examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Spurling',
    'Ortopedia',
    'Coluna',
    'Avaliar radiculopatia cervical e compressão de raiz nervosa',
    'Paciente em pé ou sentado. O examinador inclina a cabeça para o lado testado enquanto aplica compressão axial leve sobre o vértice craniano.',
    'Dor irradiada ou parestesia no trajeto do dermatoma testado',
    'Sensibilidade 50-100%, Especificidade 72-100%',
    'Spurling RG, Scoville WB, 1944',
    ARRAY['Ortopedia', 'spurling test', 'cervical radiculopathy', 'nerve compression', 'neck examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Gaveta Anterior do Tornozelo',
    'Ortopedia',
    'Tornozelo',
    'Avaliar instabilidade anterior do tornozelo (ligamento talofibular anterior)',
    'Paciente em decúbito dorsal com o joelho fletido a 90°. O examinador estabiliza a tíbia com uma mão e com a outra segura o calcanhar, tracinando o pé anteriormente.',
    'Deslocamento anterior do tálus em relação à tíbia com ponto final macio',
    'Sensibilidade 29-73%, Especificidade 70-95%',
    'van Dijk CN et al., 1996',
    ARRAY['Ortopedia', 'anterior drawer test', 'ankle instability', 'ankle examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Talar Tilt',
    'Ortopedia',
    'Tornozelo',
    'Avaliar instabilidade em inversão do tornozelo',
    'Paciente em decúbito dorsal com o joelho fletido a 90°. O examinador estabiliza a tíbia com uma mão e com a outra realiza inversão do pé, inclinando o tálus para dentro.',
    'Inclinação excessiva do tálus em relação à tíbia ou movimento anterior durante inversão',
    'Sensibilidade 18-71%, Especificidade 64-100%',
    'van Dijk CN et al., 1996',
    ARRAY['Ortopedia', 'talar tilt test', 'ankle instability', 'inversion', 'ankle examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Thompson',
    'Ortopedia',
    'Tornozelo',
    'Avaliar integridade do tendão de Aquiles',
    'Paciente em decúbito ventral com os joelhos estendidos. O examinador comprime o músculo gastrocnêmio no meio da batata da perna enquanto observa se há movimento de flexão plantar do pé.',
    'Ausência de movimento de flexão plantar do pé, sugerindo ruptura do tendão de Aquiles',
    'Sensibilidade 96-99%, Especificidade 93-99%',
    'Thompson TC, 1962',
    ARRAY['Ortopedia', 'thompson test', 'achilles tendon rupture', 'ankle examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Kleiger (Teste de Rotação Externa)',
    'Ortopedia',
    'Tornozelo',
    'Avaliar lesão da sindesmose tibiofibular',
    'Paciente em decúbito dorsal com o joelho fletido a 90°. O examinador realiza rotação externa passiva do pé enquanto estabiliza a tíbia.',
    'Dor na região anterior e lateral do tornozelo ou na sindesmose',
    'Sensibilidade 7-55%, Especificidade 93-100%',
    'Kleiger B, 1976',
    ARRAY['Ortopedia', 'kleiger test', 'syndesmotic injury', 'ankle examination', 'external rotation'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Squeeze',
    'Ortopedia',
    'Tornozelo',
    'Avaliar lesão da sindesmose tibiofibular',
    'Paciente em decúbito dorsal com o joelho estendido. O examinador comprime a fíbula e tíbia juntas no meio da perna, movendo-se proximalmente.',
    'Dor na região média ou proximal da perna, sugerindo lesão da membrana interóssea ou sindesmose',
    'Sensibilidade 13-50%, Especificidade 90-100%',
    'van Dijk CN et al., 1996',
    ARRAY['Ortopedia', 'squeeze test', 'syndesmotic injury', 'ankle examination'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),

-- ESPORTIVA --
(
    'Single Leg Hop for Distance',
    'Esportiva',
    'Joelho',
    'Avaliar força explosiva e capacidade funcional do membro inferior',
    'Paciente em pé sobre uma perna. Realiza um salto máximo para a frente sobre essa perna, aterrissando com controle. A distância é medida da linha de partida até o calcanhar do pé de aterrissagem.',
    'Simetria bilateral inferior a 90% indica déficit funcional; dor durante execução',
    'Sensibilidade 72-85%, Especificidade 65-80%',
    'Noyes FR et al., 1991',
    ARRAY['Esportiva', 'single leg hop', 'functional testing', 'lower limb assessment', 'jump test'],
    'functional_test',
    '[{"id": "distance_cm", "label": "Distância (cm)", "type": "number", "unit": "cm", "required": true}]'::jsonb
),
(
    'Triple Hop for Distance',
    'Esportiva',
    'Joelho',
    'Avaliar resistência explosiva e força explosiva do membro inferior',
    'Paciente em pé sobre uma perna. Realiza três saltos consecutivos sobre essa perna o mais longe possível, aterrissando com controle após o terceiro salto. A distância é medida do ponto inicial ao final.',
    'Simetria bilateral inferior a 90% indica déficit; dor durante execução',
    'Sensibilidade 75-90%, Especificidade 70-85%',
    'Noyes FR et al., 1991',
    ARRAY['Esportiva', 'triple hop test', 'functional assessment', 'lower limb power', 'hop test'],
    'functional_test',
    '[{"id": "distance_cm", "label": "Distância Total (cm)", "type": "number", "unit": "cm", "required": true}]'::jsonb
),
(
    'Crossover Hop for Distance',
    'Esportiva',
    'Joelho',
    'Avaliar força, agilidade e equilíbrio dinâmico',
    'Paciente em pé sobre uma perna. Realiza três saltos consecutivos cruzando a linha mediana (marcada no chão), alternando os lados do corpo enquanto se move para frente sobre uma perna. A distância total é medida.',
    'Simetria bilateral inferior a 90%; incapacidade de manter controle dinâmico',
    'Sensibilidade 78-88%, Especificidade 72-82%',
    'Noyes FR et al., 1991',
    ARRAY['Esportiva', 'crossover hop test', 'functional assessment', 'agility', 'hop test'],
    'functional_test',
    '[{"id": "distance_cm", "label": "Distância Total (cm)", "type": "number", "unit": "cm", "required": true}]'::jsonb
),
(
    '6 Meter Timed Hop',
    'Esportiva',
    'Joelho',
    'Avaliar velocidade e resistência funcional do membro inferior',
    'Paciente realiza saltos contínuos sobre uma perna pelo máximo de distância e velocidade em uma distância marcada de 6 metros. O tempo total é cronometrado.',
    'Simetria bilateral inferior a 90% em tempo; dor durante execução',
    'Sensibilidade 70-85%, Especificidade 68-80%',
    'Noyes FR et al., 1991',
    ARRAY['Esportiva', '6 meter hop test', 'timed hop', 'functional assessment', 'speed'],
    'functional_test',
    '[{"id": "time_seconds", "label": "Tempo (s)", "type": "number", "unit": "s", "step": "0.1", "required": true}]'::jsonb
),
(
    'Star Excursion Balance Test (SEBT)',
    'Esportiva',
    'Joelho',
    'Avaliar equilíbrio dinâmico, propriocepção e coordenação',
    'Paciente em pé no centro de uma estrela marcada com 8 direções. Mantém equilíbrio em uma perna enquanto toca o chão o mais longe possível em cada uma das 8 direções com a outra perna, retornando ao centro após cada alcance.',
    'Incapacidade de manter equilíbrio; assimetria bilateral maior que 4 cm em pelo menos 2 direções',
    'Sensibilidade 81-92%, Especificidade 75-88%',
    'Kinzey SJ, Armstrong CW, 1998',
    ARRAY['Esportiva', 'star excursion balance test', 'sebt', 'dynamic balance', 'proprioception'],
    'functional_test',
    '[{"id": "anterior", "label": "Anterior (cm)", "type": "number", "required": true}, {"id": "posteromedial", "label": "Posteromedial (cm)", "type": "number", "required": true}, {"id": "posterolateral", "label": "Posterolateral (cm)", "type": "number", "required": true}]'::jsonb
),
(
    'Y-Balance Test',
    'Esportiva',
    'Joelho',
    'Avaliar equilíbrio dinâmico e simetria dos membros inferiores',
    'Paciente em pé no centro da base em Y com as mãos na cintura. Equilibra-se em uma perna enquanto estende a outra o máximo possível em três direções (anterior, posterolateral, posteromedial), tocando o chão e retornando.',
    'Incapacidade de completar o teste; assimetria bilateral maior que 4 cm indicando déficit',
    'Sensibilidade 72-88%, Especificidade 70-85%',
    'Plisky PJ et al., 2006',
    ARRAY['Esportiva', 'y balance test', 'dynamic balance', 'lower limb assessment', 'proprioception'],
    'functional_test',
    '[{"id": "anterior_cm", "label": "Anterior (cm)", "type": "number", "required": true}, {"id": "pm_cm", "label": "Posteromedial (cm)", "type": "number", "required": true}, {"id": "pl_cm", "label": "Posterolateral (cm)", "type": "number", "required": true}]'::jsonb
),
(
    'Drop Jump Test (Valgo Dinâmico)',
    'Esportiva',
    'Joelho',
    'Avaliar alinhamento e controle dinâmico do joelho durante aterrissagem',
    'Paciente fica em pé em uma plataforma elevada (30-40 cm). Salta para baixo e aterrissa em uma posição de semi-agachamento natural, mantendo uma distância de 45 cm entre os pés.',
    'Joelho em valgo excessivo, pronação de tornozelo, ou anteverção de pelve durante aterrissagem',
    'Sensibilidade 80-92%, Especificidade 78-89%',
    'Munro A et al., 2012',
    ARRAY['Esportiva', 'drop jump test', 'knee valgus', 'landing mechanics', 'jump assessment'],
    'functional_test',
    '[{"id": "valgus_quality", "label": "Qualidade do Valgo", "type": "select", "options": ["Bom", "Moderado", "Ruim"], "required": true}]'::jsonb
),
(
    'Tuck Jump Assessment',
    'Esportiva',
    'Joelho',
    'Avaliar controle neuromuscular e técnica de salto',
    'Paciente realiza saltos contínuos por 10 segundos, trazendo os joelhos o máximo possível em direção ao peito durante cada salto, mantendo a postura ereta.',
    'Falha em trazer os joelhos para cima; queda de postura; desvio de alinhamento do joelho',
    'Sensibilidade 82-94%, Especificidade 80-90%',
    'Myer GD et al., 2008',
    ARRAY['Esportiva', 'tuck jump assessment', 'neuromuscular control', 'jump technique', 'knee alignment'],
    'functional_test',
    '[{"id": "technique_score", "label": "Pontuação de Técnica", "type": "number", "min": 0, "max": 10, "required": true}]'::jsonb
),
(
    'Lunge Test (Knee to Wall)',
    'Esportiva',
    'Joelho',
    'Avaliar mobilidade de tornozelo e dorsiflexão',
    'Paciente em posição de lunge com a perna traseira estendida. O pé dianteiro é posicionado a uma distância da parede. O paciente realiza lunge mantendo o calcanhar apoiado enquanto tenta tocar o joelho na parede.',
    'Incapacidade de tocar o joelho na parede ou deslocamento do calcanhar durante movimento',
    'Sensibilidade 75-88%, Especificidade 70-85%',
    'Rabin A et al., 2014',
    ARRAY['Esportiva', 'lunge test', 'ankle mobility', 'dorsiflexion', 'knee to wall'],
    'functional_test',
    '[{"id": "distance_cm", "label": "Distância (cm)", "type": "number", "unit": "cm", "required": true}]'::jsonb
),

-- PÓS OPERATÓRIO --
(
    'Teste de Estabilidade Rotacional do Tornozelo',
    'Pós-Operatório',
    'Tornozelo',
    'Avaliar controle neuromuscular e propriocepção pós-operatória',
    'Paciente em pé sobre uma superfície instável (almofada de equilíbrio ou disco proprioceptivo) sobre um pé. Mantém a posição o máximo possível enquanto o examinador observa oscilações e equilíbrio.',
    'Incapacidade de manter equilíbrio por 30 segundos; oscilações excessivas',
    'Sensibilidade 85-95%, Especificidade 82-92%',
    'Hertel J, 2002',
    ARRAY['Pós-Operatório', 'PosOp', 'ankle stability test', 'proprioception', 'balance assessment', 'postoperative'],
    'functional_test',
    '[{"id": "time_seconds", "label": "Tempo de Equilíbrio (s)", "type": "number", "unit": "s", "required": true}]'::jsonb
),
(
    'Teste de Extensão Ativa do Joelho Pós-Operatório',
    'Pós-Operatório',
    'Joelho',
    'Avaliar recuperação funcional do quadríceps após cirurgia',
    'Paciente sentado com um apoio sob o joelho. Realiza extensão ativa completa do joelho contra a gravidade, mantendo a posição por 5 segundos.',
    'Incapacidade de realizar extensão completa; fraqueza significativa; derrame articular',
    'Sensibilidade 88-96%, Especificidade 85-93%',
    'Matassi F et al., 2014',
    ARRAY['Pós-Operatório', 'PosOp', 'active knee extension', 'quadriceps strength', 'postoperative assessment'],
    'functional_test',
    '[{"id": "lag_degrees", "label": "Lag de Extensão (graus)", "type": "number", "unit": "graus", "required": true}]'::jsonb
),
(
    'Teste de Amplitude de Movimento do Ombro Pós-Operatório',
    'Pós-Operatório',
    'Ombro',
    'Avaliar recuperação de amplitude articular após cirurgia de manguito rotador',
    'Paciente em pé ou sentado. O examinador realiza medições passivas e ativas de flexão anterior, abdução, rotação interna e externa do ombro utilizando goniômetro.',
    'Déficit de amplitude comparado ao lado contralateral em mais de 20°; dor durante movimento',
    'Sensibilidade 82-94%, Especificidade 80-90%',
    'Turk DC et al., 2016',
    ARRAY['Pós-Operatório', 'PosOp', 'shoulder rom test', 'range of motion', 'postoperative assessment', 'rotator cuff'],
    'functional_test',
    '[{"id": "flexion_rom", "label": "Flexão (graus)", "type": "number", "required": true}, {"id": "abduction_rom", "label": "Abdução (graus)", "type": "number", "required": true}]'::jsonb
);
