-- Seed Clinical Tests Library (PhysioTests Pro)
-- Cleans up existing templates to avoid duplicates (re-runnable)
DELETE FROM clinical_test_templates WHERE organization_id IS NULL;

INSERT INTO clinical_test_templates (name, name_en, category, target_joint, purpose, execution, positive_sign, sensitivity_specificity, reference, media_placeholder_keywords, tags, type, fields_definition) VALUES

-- ORTOPEDIA: OMBRO --
(
    'Teste de Neer',
    'Neer Test',
    'Ortopedia',
    'Ombro',
    'Avaliar impacto subacromial (síndrome do impacto no ombro)',
    'Paciente sentado. Terapeuta estabiliza a escápula do paciente com uma mão e, com a outra, eleva passivamente o braço em flexão completa do ombro (geralmente com rotação interna).',
    'Dor no aspecto ântero-lateral do ombro reproduzindo a dor referida pelo paciente indica teste positivo para impacto subacromial.',
    '59-72% sensibilidade, 6% especificidade',
    'Hegedus, 2012',
    ARRAY['neer test', 'shoulder impingement test'],
    ARRAY['Ortopedia', 'Ombro', 'Impacto', 'Neer'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Hawkins-Kennedy',
    'Hawkins-Kennedy Test',
    'Ortopedia',
    'Ombro',
    'Avaliar impacto subacromial (impingement de estruturas subacromiais)',
    'Paciente sentado, ombro e cotovelo flexionados a 90°. Terapeuta estabiliza a escápula com uma mão e, com a outra no cotovelo, realiza rotação interna passiva e forçada do ombro.',
    'Dor no ombro reproduzindo a dor do paciente indica teste positivo para síndrome do impacto subacromial.',
    '58-80% sensibilidade, 56-67% especificidade',
    'Hegedus, 2012',
    ARRAY['hawkins kennedy test', 'shoulder impingement'],
    ARRAY['Ortopedia', 'Ombro', 'Impacto', 'Hawkins'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Jobe (Empty Can)',
    'Jobe Test (Empty Can)',
    'Ortopedia',
    'Ombro',
    'Avaliar lesão ou tendinopatia do músculo supraespinhal (manguito rotador)',
    'Paciente em pé ou sentado. Braços elevados a 90° no plano da escápula. Em seguida, o paciente roda internamente os ombros (polegares para baixo). O terapeuta aplica pressão para baixo nos antebraços e o paciente resiste.',
    'Dor ou fraqueza comparativa no braço afetado em relação ao lado oposto indica lesão do tendão do supraespinhal.',
    '74% sensibilidade, 30% especificidade',
    'Hegedus, 2012',
    ARRAY['empty can test', 'supraspinatus test'],
    ARRAY['Ortopedia', 'Ombro', 'Supraespinhal', 'Jobe'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste Full Can (Lata Cheia)',
    'Full Can Test',
    'Ortopedia',
    'Ombro',
    'Avaliar lesão do músculo supraespinhal, com menor compressão subacromial que o teste Empty Can',
    'Paciente em pé ou sentado, braços elevados a 90° no plano escapular com polegares apontando para cima (rotação externa). O paciente resiste à pressão para baixo aplicada pelo terapeuta sobre os braços.',
    'Dor ou fraqueza em comparação com o lado contralateral sugerem lesão do tendão do supraespinhal.',
    '70% sensibilidade, 81% especificidade',
    'Jain, 2017',
    ARRAY['full can test', 'supraspinatus test'],
    ARRAY['Ortopedia', 'Ombro', 'Supraespinhal'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Speed',
    'Speed''s Test',
    'Ortopedia',
    'Ombro',
    'Avaliar tendinopatia do tendão da cabeça longa do bíceps ou lesão tipo SLAP',
    'Paciente sentado ou em pé. Paciente com ombro em flexão anterior de 90°, cotovelo estendido e antebraço supinado. O terapeuta aplica resistência à elevação do braço ou pressão para baixo enquanto o paciente tenta manter a posição.',
    'Dor no sulco bicipital durante a resistência é indicativa de tendinopatia do bíceps ou lesão do labrum superior (SLAP).',
    '20% sensibilidade, 78% especificidade',
    'Hegedus, 2012',
    ARRAY['speed''s test', 'biceps tendon test'],
    ARRAY['Ortopedia', 'Ombro', 'Bíceps', 'SLAP'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Yergason',
    'Yergason Test',
    'Ortopedia',
    'Ombro',
    'Avaliar estabilidade do tendão do bíceps (ligamento transverso) e possível lesão SLAP ou tendinopatia bicipital',
    'Paciente sentado com cotovelo flexionado a 90° junto ao tronco e antebraço pronado. Terapeuta segura a mão do paciente e pede para ele supinar o antebraço contra resistência, enquanto palpa o tendão do bíceps no sulco bicipital.',
    'Dor localizada no sulco bicipital indica tendinopatia do bíceps ou possível lesão SLAP. Sensação de translação ou estalido do tendão do bíceps saindo do sulco indica ruptura do ligamento umeral transverso.',
    '32% sensibilidade, 88% especificidade',
    'Micheroli, 2015',
    ARRAY['yergason test', 'biceps tendon test'],
    ARRAY['Ortopedia', 'Ombro', 'Bíceps', 'SLAP'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de O''Brien (Compressão Ativa)',
    'O''Brien Test (Active Compression)',
    'Ortopedia',
    'Ombro',
    'Detectar lesões do lábio superior (lesão SLAP) e/ou patologia da articulação acromioclavicular',
    'Paciente em pé com ombro a 90° de flexão e 10° de adução horizontal. Primeiro, com polegar apontando para baixo (rotação interna do ombro), o paciente resiste à pressão para baixo aplicada pelo terapeuta. Em seguida, com polegar para cima (rotação externa), o paciente resiste novamente à pressão para baixo.',
    'Dor profunda no ombro presente na primeira posição de teste (rotação interna) que diminui ou desaparece na segunda posição (rotação externa) sugere lesão SLAP. Dor localizada sobre a articulação acromioclavicular durante o teste pode indicar lesão na articulação AC.',
    '67% sensibilidade, 37% especificidade (SLAP)',
    'Hegedus, 2012',
    ARRAY['obrien test', 'SLAP lesion test'],
    ARRAY['Ortopedia', 'Ombro', 'SLAP', 'AC'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Apreensão Anterior do Ombro',
    'Shoulder Apprehension Test',
    'Ortopedia',
    'Ombro',
    'Avaliar instabilidade anterior glenoumeral (propensão à luxação anterior do ombro)',
    'Paciente em decúbito dorsal próximo à borda da mesa. Com o ombro abduzido a 90° e cotovelo a 90°, o terapeuta lentamente realiza rotação externa máxima do ombro, observando a reação do paciente. O paciente deve ser instruído a relatar qualquer apreensão ou sensação de instabilidade durante o movimento.',
    'Expressão de receio ou apreensão do paciente, ou resistência ao movimento por medo de luxação, indica teste positivo para instabilidade anterior do ombro.',
    '66% sensibilidade, 95% especificidade',
    'Hegedus, 2012',
    ARRAY['shoulder apprehension test', 'anterior instability test'],
    ARRAY['Ortopedia', 'Ombro', 'Instabilidade'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Relocação do Ombro',
    'Shoulder Relocation Test',
    'Ortopedia',
    'Ombro',
    'Confirmar instabilidade anterior do ombro, aliviando os sintomas de apreensão do teste de apreensão',
    'Realizado imediatamente após um teste de apreensão anterior positivo. Com o paciente em decúbito dorsal, ombro a 90° de abdução e próximo ao ponto de apreensão (durante rotação externa), o terapeuta aplica uma pressão firme em sentido póstero-lateral sobre a cabeça do úmero (empurrando a cabeça do úmero posteriormente).',
    'Redução ou alívio da sensação de apreensão ou dor do paciente quando aplicada a pressão posterior indica teste positivo, confirmando instabilidade anterior glenoumeral.',
    '65% sensibilidade, 90% especificidade',
    'Hegedus, 2012',
    ARRAY['relocation test shoulder', 'anterior instability test'],
    ARRAY['Ortopedia', 'Ombro', 'Instabilidade'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Queda do Braço (Drop Arm)',
    'Drop Arm Test',
    'Ortopedia',
    'Ombro',
    'Avaliar roturas de espessura total do manguito rotador, especialmente do tendão do supraespinhal (e infraespinhal)',
    'Paciente em pé. Terapeuta eleva passivamente o braço do paciente para aproximadamente 90° de abdução. Em seguida, pede-se ao paciente para sustentar essa posição e, então, liberar o suporte do braço, solicitando que o paciente controle lentamente a descida do braço.',
    'Incapacidade do paciente de sustentar o braço abduzido ou de controlá-lo lentamente em descida (o braço cai repentinamente) indica possível ruptura completa do tendão do supraespinhal (sinal do braço caído).',
    '73% sensibilidade, 77% especificidade',
    'Miller, 2008',
    ARRAY['drop arm test', 'rotator cuff tear test'],
    ARRAY['Ortopedia', 'Ombro', 'Manguito Rotador'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Gerber (Lift-Off)',
    'Gerber Lift-Off Test',
    'Ortopedia',
    'Ombro',
    'Avaliar integridade do músculo subescapular (ruptura ou lesão do tendão do subescapular)',
    'Paciente em pé, com o dorso da mão apoiado na região lombar (coluna lombar). Pede-se ao paciente que tente levantar a mão para longe das costas (em direção à posterior). Se conseguir, o terapeuta pode aplicar resistência contra a mão para testar a força.',
    'Incapacidade de levantar a mão das costas indica lesão ou ruptura do músculo e/ou tendão subescapular. Movimento anormal da escápula durante o teste também pode indicar compensação por fraqueza do subescapular.',
    '22% sensibilidade, 94% especificidade',
    'Jain, 2017',
    ARRAY['lift off test', 'gerber test subscapularis'],
    ARRAY['Ortopedia', 'Ombro', 'Subescapular'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste da Pressão Abdominal (Belly Press)',
    'Belly Press Test',
    'Ortopedia',
    'Ombro',
    'Avaliar lesão do tendão do subescapular, especialmente em casos em que o lift-off não pode ser executado devido à dor ou restrição de movimento',
    'Paciente em pé ou sentado. Paciente coloca a palma da mão do ombro avaliado sobre seu abdome, logo abaixo do esterno, e tenta pressionar a mão contra o abdome ativamente. O terapeuta observa a posição do cotovelo do paciente durante a manobra.',
    'Incapacidade de manter o cotovelo apontado para frente ou necessidade de flexionar o punho (deslocando o cotovelo posteriormente) para empurrar indica fraqueza/lesão do subescapular (teste positivo, também chamado "sinal de Napoleão").',
    '40% sensibilidade, 98% especificidade',
    'Burkhart, 2002',
    ARRAY['belly press test', 'napoleon test subscapularis'],
    ARRAY['Ortopedia', 'Ombro', 'Subescapular'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste do Abraço de Urso (Bear Hug)',
    'Bear Hug Test',
    'Ortopedia',
    'Ombro',
    'Avaliar lesão do tendão do subescapular (alternativa para testar subescapular)',
    'Paciente em pé. Pede-se para colocar a palma da mão do lado afetado sobre o ombro oposto (tocando o ombro contralateral), com o cotovelo apontado para frente. O terapeuta tenta puxar a mão do paciente para longe do ombro (aplicando força de rotação externa no antebraço) enquanto o paciente resiste tentando manter a mão no ombro.',
    'Incapacidade de manter a mão no ombro contralateral contra a resistência ou dor significativa no ombro durante o teste indicam lesão do subescapular.',
    'Variável',
    'Barth, 2006',
    ARRAY['bear hug test', 'subscapularis tear test'],
    ARRAY['Ortopedia', 'Ombro', 'Subescapular'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Sinal do Sulco (Sulcus Sign)',
    'Sulcus Sign',
    'Ortopedia',
    'Ombro',
    'Identificar instabilidade inferior ou multidirecional do ombro (laxidez capsuloligamentar)',
    'Paciente sentado ou em pé, com o braço relaxado ao lado do corpo. O terapeuta segura o braço do paciente distalmente ao cotovelo e aplica tração para baixo (direção inferior) no úmero, observando a região logo abaixo do acrômio.',
    'Aparição de um sulco ou depressão evidente abaixo do acrômio (entre a cabeça do úmero e o acrômio) durante a tração indica instabilidade inferior do ombro (teste positivo).',
    'Variável',
    'Neviaser, 1989',
    ARRAY['sulcus sign shoulder', 'inferior instability test'],
    ARRAY['Ortopedia', 'Ombro', 'Instabilidade'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Lachman',
    'Lachman Test',
    'Ortopedia',
    'Joelho',
    'Avaliar integridade do Ligamento Cruzado Anterior (LCA)',
    'Paciente em decúbito dorsal. Joelho testado flexionado em ~30°. Terapeuta estabiliza o fêmur distal com uma mão enquanto a outra mão envolve a tíbia proximal (ligeira rotação externa) e aplica uma translação anterior rápida da tíbia em relação ao fêmur.',
    'Movimento excessivo da tíbia para frente (comparado ao lado saudável) ou sensação de fim de curso macio (ausência de end feel firme) indicam ruptura do LCA.',
    '85% sensibilidade, 94% especificidade',
    'Benjaminse, 2006',
    ARRAY['lachman test', 'knee ACL test'],
    ARRAY['Ortopedia', 'Joelho', 'LCA'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste da Gaveta Anterior (Joelho)',
    'Anterior Drawer Test',
    'Ortopedia',
    'Joelho',
    'Avaliar lesão do Ligamento Cruzado Anterior (LCA)',
    'Paciente em decúbito dorsal com joelho flexionado a 90° e pé apoiado na maca. Terapeuta senta-se sobre o pé do paciente para estabilizá-lo, posiciona ambas as mãos na porção proximal da tíbia (polegares na linha articular) e puxa a tíbia anteriormente (em direção a si) de forma firme.',
    'Deslizamento anterior excessivo da tíbia sob o fêmur em comparação com o joelho contralateral, especialmente com ausência de ponto final firme, indica ruptura do LCA.',
    '92% sensibilidade, 91% especificidade',
    'Benjaminse, 2006',
    ARRAY['anterior drawer test knee', 'ACL tear test'],
    ARRAY['Ortopedia', 'Joelho', 'LCA'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste da Gaveta Posterior',
    'Posterior Drawer Test',
    'Ortopedia',
    'Joelho',
    'Avaliar integridade do Ligamento Cruzado Posterior (LCP)',
    'Paciente em decúbito dorsal com joelho flexionado a 90° e pé apoiado. Terapeuta estabiliza o pé do paciente (sentando sobre o pé) e coloca as mãos na tíbia proximal. Em seguida, empurra a tíbia posteriormente (para trás) em relação ao fêmur, aplicando força na linha articular do joelho.',
    'Translação posterior excessiva da tíbia (deslocamento para trás) comparada ao lado oposto indica lesão/ruptura do LCP.',
    '89% sensibilidade, 98% especificidade',
    'Rubinstein, 1994',
    ARRAY['posterior drawer test knee', 'PCL tear test'],
    ARRAY['Ortopedia', 'Joelho', 'LCP'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Pivot-Shift',
    'Pivot Shift Test',
    'Ortopedia',
    'Joelho',
    'Avaliar instabilidade rotatória ântero-lateral do joelho (ruptura do LCA)',
    'Paciente em decúbito dorsal. Terapeuta segura a perna do paciente estendida pelo calcanhar, aplica rotação interna na tíbia e um estresse em valgo no joelho. Em seguida, flexiona-se lentamente o joelho a partir da extensão completa. O examinador sente/observa o comportamento da tíbia durante a flexão.',
    'Em um joelho com LCA rompido, a tíbia subluxa anteriormente quando o joelho está quase em extensão e, ao iniciar a flexão (~30°), a tíbia reduz subitamente com um "clunk" ou ressalto palpável. Esse salto indica um teste de pivot-shift positivo.',
    '24% sensibilidade, 98% especificidade',
    'Benjaminse, 2006',
    ARRAY['pivot shift test', 'ACL instability test'],
    ARRAY['Ortopedia', 'Joelho', 'LCA'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Estresse em Valgo (Joelho)',
    'Valgus Stress Test',
    'Ortopedia',
    'Joelho',
    'Avaliar integridade do Ligamento Colateral Medial (LCM) do joelho',
    'Paciente em decúbito dorsal. Com o joelho inicialmente em extensão completa (0°) e depois em ~30° de flexão, o terapeuta estabiliza o tornozelo com uma mão e posiciona a outra mão na face lateral do joelho. Aplica-se então uma força em valgo no joelho para abrir a articulação medialmente.',
    'Dor excessiva na linha articular medial ou aumento da abertura (folga) medial do joelho em comparação com o lado contralateral indica lesão do LCM.',
    '78% sensibilidade, 67% especificidade',
    'Kastelein, 2008',
    ARRAY['valgus stress test knee', 'MCL test'],
    ARRAY['Ortopedia', 'Joelho', 'LCM'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Estresse em Varo (Joelho)',
    'Varus Stress Test',
    'Ortopedia',
    'Joelho',
    'Avaliar integridade do Ligamento Colateral Lateral (LCL) do joelho',
    'Paciente em decúbito dorsal. Com o joelho inicialmente em extensão total e depois levemente flexionado (~30°), o terapeuta estabiliza o tornozelo e posiciona a outra mão na face medial do joelho. Aplica uma força em varo para estressar o compartimento lateral do joelho.',
    'Dor localizada na linha articular lateral ou instabilidade (abertura lateral aumentada) comparada ao outro joelho indica lesão do LCL.',
    'Baixa sensibilidade (~25%)',
    'LaPrade, 2014',
    ARRAY['varus stress test knee', 'LCL test'],
    ARRAY['Ortopedia', 'Joelho', 'LCL'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de McMurray',
    'McMurray Test',
    'Ortopedia',
    'Joelho',
    'Avaliar lesões de menisco (medial ou lateral)',
    'Paciente em decúbito dorsal. Com o joelho em flexão máxima, o terapeuta realiza rotação da tíbia (interna para lateral, externa para medial) e estende lentamente o joelho.',
    'Um estalido audível ou palpável, ou dor aguda na linha articular correspondente durante o movimento de extensão do joelho, indica um teste de McMurray positivo.',
    '61% sensibilidade, 84% especificidade',
    'Smith, 2015',
    ARRAY['mcmurray test', 'meniscus test'],
    ARRAY['Ortopedia', 'Joelho', 'Menisco'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Apley (Grinding Test)',
    'Apley Grind Test',
    'Ortopedia',
    'Joelho',
    'Diferenciar lesão de menisco vs. lesão ligamentar colateral no joelho',
    'Paciente em decúbito ventral com joelho a ~90°. Terapeuta aplica tração com rotação (ligamento) e compressão com rotação (menisco).',
    'Dor ao movimento com compressão axial, que alivia com a tração, sugere lesão meniscal. Se a dor for maior com tração e rotação, sugere lesão ligamentar.',
    '61% sensibilidade, 70% especificidade',
    'Hegedus, 2007',
    ARRAY['apley test', 'meniscus test'],
    ARRAY['Ortopedia', 'Joelho', 'Menisco'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Thessaly',
    'Thessaly Test',
    'Ortopedia',
    'Joelho',
    'Avaliar lesões de menisco de forma dinâmica com carga',
    'Paciente em pé apoiado pelo terapeuta e em apoio unipodal com joelho a 20°. Realiza rotações do tronco para a direita e esquerda 3 vezes.',
    'Dor na linha articular medial ou lateral do joelho, ou sensação de falseio/click durante a rotação em apoio monopodal.',
    '64% sensibilidade, 53% especificidade',
    'Goossens, 2015',
    ARRAY['thessaly test', 'meniscus test'],
    ARRAY['Ortopedia', 'Joelho', 'Menisco'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Apreensão Patelar (Sinal de Fairbank)',
    'Patellar Apprehension Test',
    'Ortopedia',
    'Joelho',
    'Avaliar instabilidade patelar lateral',
    'Paciente em decúbito dorsal. Terapeuta desliza a patela lateralmente. Pode ser repetido a 30° de flexão.',
    'Expressão de apreensão, contracção súbita do quadríceps ou relutância do paciente indicando medo de deslocamento da patela.',
    '61% sensibilidade, 84% especificidade',
    'Näslund, 2006',
    ARRAY['patellar apprehension test', 'patella dislocation test'],
    ARRAY['Ortopedia', 'Joelho', 'Patela'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Sinal de Clarke (Patellar Grind Test)',
    'Clarke''s Sign',
    'Ortopedia',
    'Joelho',
    'Detectar condromalácia patelar ou síndrome da dor patelofemoral',
    'Paciente em decúbito dorsal. Terapeuta pressiona a patela distalmente e pede contração do quadríceps.',
    'Dor retropatelar significativa ou desconforto durante a contração do quadríceps.',
    'Variável',
    'Cook, 2012',
    ARRAY['clarke sign', 'patellar grind test'],
    ARRAY['Ortopedia', 'Joelho', 'Patela'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Sinal de Gaveta Posterior (Sinal de Godfrey)',
    'Godfrey''s Test (Sag Sign)',
    'Ortopedia',
    'Joelho',
    'Identificar translação posterior anormal da tíbia (LCP)',
    'Paciente em decúbito dorsal, quadris e joelhos flexionados a 90°. Observa-se a tuberosidade tibial.',
    'Desnível posterior da tuberosidade tibial no joelho lesionado (tíbia "afunda").',
    '79% sensibilidade, 100% especificidade',
    'Rubinstein, 1994',
    ARRAY['sag sign knee', 'Godfrey test PCL'],
    ARRAY['Ortopedia', 'Joelho', 'LCP'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Thomas',
    'Thomas Test',
    'Ortopedia',
    'Quadril',
    'Avaliar encurtamento ou contratura dos flexores de quadril',
    'Paciente em decúbito dorsal. Flexiona um joelho ao peito e segura. Observa-se a perna oposta estendida.',
    'Se a coxa do membro oposto levantar-se da maca.',
    'Variável',
    'Harvey, 1998',
    ARRAY['thomas test hip', 'hip flexor tightness test'],
    ARRAY['Ortopedia', 'Quadril', 'Flexibilidade'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de FABER (Patrick)',
    'FABER Test',
    'Ortopedia',
    'Quadril',
    'Avaliar patologia do quadril ou disfunção sacroilíaca',
    'Posição de "4" (Flexão, Abdução, Rot. Externa). Pressão no joelho em direção à maca.',
    'Dor inguinal (quadril) ou sacroilíaca (posterior).',
    'Variável',
    'Manion, 2008',
    ARRAY['FABER test', 'Patrick test hip'],
    ARRAY['Ortopedia', 'Quadril', 'Sacroilíaca'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de FADIR',
    'FADIR Test',
    'Ortopedia',
    'Quadril',
    'Avaliar impacto femoroacetabular anterior (FAI) e lesões labrais',
    'Flexão 90°, Adução e Rotação Interna do quadril.',
    'Dor na virilha ou sensação de pinçamento.',
    'Variável',
    'Martin, 2011',
    ARRAY['FADIR test', 'hip impingement test'],
    ARRAY['Ortopedia', 'Quadril', 'Impacto'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Ely',
    'Ely''s Test',
    'Ortopedia',
    'Quadril',
    'Avaliar encurtamento do músculo reto femoral',
    'Paciente em decúbito ventral. Flexão passiva do joelho com calcanhar na nádega.',
    'Elevação da pelve (antecversão) no lado testado.',
    'Variável',
    'Worrel, 1991',
    ARRAY['ely''s test', 'rectus femoris tightness'],
    ARRAY['Ortopedia', 'Quadril', 'Flexibilidade'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Ober',
    'Ober Test',
    'Ortopedia',
    'Quadril',
    'Avaliar contratura da banda iliotibial e tensor da fáscia lata',
    'Decúbito lateral. Abdução e extensão da perna superior, depois solta em adução.',
    'Perna permanece elevada e não aduz até a linha do corpo.',
    'Variável',
    'Gajdosik, 2003',
    ARRAY['ober test', 'IT band tightness test'],
    ARRAY['Ortopedia', 'Quadril', 'Flexibilidade'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Sinal de Trendelenburg',
    'Trendelenburg Sign',
    'Ortopedia',
    'Quadril',
    'Avaliar fraqueza dos abdutores (glúteo médio)',
    'Apoio unipodal por 30s.',
    'Queda da pelve do lado oposto ou inclinação do tronco.',
    'Variável',
    'Hardcastle, 1984',
    ARRAY['trendelenburg sign', 'gluteus medius weakness'],
    ARRAY['Ortopedia', 'Quadril', 'Força'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Lasègue (SLR)',
    'Straight Leg Raise (SLR)',
    'Ortopedia',
    'Coluna',
    'Avaliar irritação do nervo ciático (radiculopatia)',
    'Elevação passiva da perna estendida em decúbito dorsal.',
    'Dor ciática entre 30°-70° de elevação.',
    'Variável',
    'DeLasègue, 1864',
    ARRAY['straight leg raise test', 'Lasegue test sciatica'],
    ARRAY['Ortopedia', 'Coluna', 'Ciático'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Slump',
    'Slump Test',
    'Ortopedia',
    'Coluna',
    'Avaliar tensão neural e raízes nervosas',
    'Sentado, flexão torácica/lombar e cervical. Extensão do joelho e dorsiflexão.',
    'Reprodução de dor ciática que alivia com extensão cervical.',
    'Variável',
    'Maitland, 1985',
    ARRAY['slump test', 'neural tension test'],
    ARRAY['Ortopedia', 'Coluna', 'Neural'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Spurling',
    'Spurling Test',
    'Ortopedia',
    'Coluna',
    'Avaliar radiculopatia cervical',
    'Extensão, inclinação lateral da cabeça e compressão axial.',
    'Dor irradiada no membro superior.',
    'Variável',
    'Spurling, 1944',
    ARRAY['spurling test', 'cervical radiculopathy test'],
    ARRAY['Ortopedia', 'Coluna', 'Cervical'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Gaenslen',
    'Gaenslen Test',
    'Ortopedia',
    'Coluna',
    'Avaliar disfunção sacroilíaca',
    'Decúbito dorsal na borda. Uma perna flexionada ao peito, outra estendida para fora da maca.',
    'Dor na região sacroilíaca do lado estendido.',
    'Variável',
    'Laslett, 2005',
    ARRAY['gaenslen test', 'SI joint test'],
    ARRAY['Ortopedia', 'Coluna', 'Sacroilíaca'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste da Gaveta Anterior do Tornozelo',
    'Anterior Drawer Test (Ankle)',
    'Ortopedia',
    'Tornozelo',
    'Avaliar lesão do ligamento talofibular anterior (LTFA)',
    'Estabiliza tíbia, puxa calcâneo anteriormente.',
    'Translação anterior excessiva do tálus.',
    'Variável',
    'van Dijk, 1996',
    ARRAY['ankle anterior drawer test', 'ATFL tear test'],
    ARRAY['Ortopedia', 'Tornozelo', 'Instabilidade'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Inclinação Talar (Talar Tilt)',
    'Talar Tilt Test',
    'Ortopedia',
    'Tornozelo',
    'Avaliar ligamentos colaterais (lateral e medial)',
    'Inversão (lateral) ou eversão (medial) forçada do retropé.',
    'Dor ou amplitude excessiva comparada ao lado oposto.',
    'Variável',
    'Krause, 1995',
    ARRAY['talar tilt test', 'ankle instability test'],
    ARRAY['Ortopedia', 'Tornozelo', 'Instabilidade'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Thompson',
    'Thompson Test',
    'Ortopedia',
    'Tornozelo',
    'Detectar ruptura do tendão de Aquiles',
    'Decúbito ventral. Compressão da panturrilha.',
    'Ausência de flexão plantar do pé.',
    '96% sensibilidade, 93% especificidade',
    'Matles, 1975',
    ARRAY['thompson test', 'achilles tendon rupture test'],
    ARRAY['Ortopedia', 'Tornozelo', 'Aquiles'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Kleiger (Rotação Externa)',
    'Kleiger Test',
    'Ortopedia',
    'Tornozelo',
    'Avaliar sindesmose ou ligamento deltóide',
    'Rotação externa forçada do pé.',
    'Dor na sindesmose (lateral) ou deltóide (medial).',
    'Variável',
    'Kleiger, 1956',
    ARRAY['kleiger test', 'external rotation stress ankle'],
    ARRAY['Ortopedia', 'Tornozelo', 'Sindesmose'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Teste de Squeeze',
    'Squeeze Test',
    'Ortopedia',
    'Tornozelo',
    'Detectar lesão da sindesmose',
    'Compressão de tíbia e fíbula na panturrilha.',
    'Dor distal na sindesmose.',
    'Variável',
    'Hopkinson, 1990',
    ARRAY['squeeze test ankle', 'syndesmosis test'],
    ARRAY['Ortopedia', 'Tornozelo', 'Sindesmose'],
    'special_test',
    '[{"id": "result", "label": "Resultado", "type": "select", "options": ["Positivo", "Negativo"], "required": true}]'::jsonb
),
(
    'Single Leg Hop for Distance',
    'Single Leg Hop for Distance',
    'Pós-Operatório',
    'Joelho',
    'Avaliar capacidade funcional (retorno ao esporte pós-LCA)',
    'Salto horizontal máximo em uma perna.',
    'Simetria < 90% comparado ao lado oposto.',
    'Variável',
    'Noyes, 1991',
    ARRAY['single leg hop test', 'ACL return to sport test'],
    ARRAY['Esportiva', 'Pós-Operatório', 'Joelho'],
    'functional_test',
    '[{"id": "distance_cm", "label": "Distância (cm)", "type": "number", "unit": "cm", "required": true}]'::jsonb
),
(
    'Triple Hop for Distance',
    'Triple Hop for Distance',
    'Pós-Operatório',
    'Joelho',
    'Avaliar potência e estabilidade (3 saltos)',
    'Três saltos consecutivos em uma perna.',
    'Simetria < 90%.',
    'Variável',
    'Noyes, 1991',
    ARRAY['triple hop test', 'ACL functional test'],
    ARRAY['Esportiva', 'Pós-Operatório', 'Joelho'],
    'functional_test',
    '[{"id": "distance_cm", "label": "Distância Total (cm)", "type": "number", "unit": "cm", "required": true}]'::jsonb
),
(
    'Crossover Hop Test',
    'Crossover Hop Test',
    'Pós-Operatório',
    'Joelho',
    'Avaliar agilidade e estabilidade com mudança de direção',
    'Três saltos cruzando uma linha.',
    'Simetria < 90%.',
    'Variável',
    'Noyes, 1991',
    ARRAY['crossover hop test', 'ACL functional test'],
    ARRAY['Esportiva', 'Pós-Operatório', 'Joelho'],
    'functional_test',
    '[{"id": "distance_cm", "label": "Distância Total (cm)", "type": "number", "unit": "cm", "required": true}]'::jsonb
),
(
    '6m Timed Hop Test',
    '6m Timed Hop Test',
    'Pós-Operatório',
    'Joelho',
    'Avaliar velocidade e potência em 6 metros',
    'Tempo para saltar 6m em uma perna.',
    'Tempo > 10% mais lento que o lado oposto.',
    'Variável',
    'Barber-Westin, 2011',
    ARRAY['6m timed hop test', 'ACL hop test'],
    ARRAY['Esportiva', 'Pós-Operatório', 'Joelho'],
    'functional_test',
    '[{"id": "time_seconds", "label": "Tempo (s)", "type": "number", "unit": "s", "step": "0.1", "required": true}]'::jsonb
),
(
    'Star Excursion Balance Test (SEBT)',
    'Star Excursion Balance Test (SEBT)',
    'Esportiva',
    'Tornozelo',
    'Avaliar equilíbrio dinâmico em 8 direções',
    'Alcance máximo em 8 direções em apoio unipodal.',
    'Assimetria > 4cm.',
    'Variável',
    'Kinzey, 1998',
    ARRAY['star excursion balance test', 'balance reach test'],
    ARRAY['Esportiva', 'Tornozelo', 'Equilíbrio'],
    'functional_test',
    '[{"id": "anterior", "label": "Anterior (cm)", "type": "number", "required": true}, {"id": "posteromedial", "label": "Posteromedial (cm)", "type": "number", "required": true}, {"id": "posterolateral", "label": "Posterolateral (cm)", "type": "number", "required": true}]'::jsonb
),
(
    'Teste Y-Balance',
    'Y-Balance Test',
    'Esportiva',
    'Tornozelo',
    'Avaliar equilíbrio dinâmico simplificado (3 direções)',
    'Alcance em Y (Anterior, PM, PL) em apoio unipodal.',
    'Assimetria > 4cm.',
    'Variável',
    'Plisky, 2009',
    ARRAY['y balance test', 'balance reach test'],
    ARRAY['Esportiva', 'Tornozelo', 'Equilíbrio'],
    'functional_test',
    '[{"id": "anterior_cm", "label": "Anterior (cm)", "type": "number", "required": true}, {"id": "pm_cm", "label": "Posteromedial (cm)", "type": "number", "required": true}, {"id": "pl_cm", "label": "Posterolateral (cm)", "type": "number", "required": true}]'::jsonb
),
(
    'Drop Jump Test',
    'Drop Jump Test',
    'Esportiva',
    'Joelho',
    'Avaliar valgo dinâmico e risco de LCA',
    'Salto de caixa com salto vertical imediato.',
    'Valgo dinâmico excessivo.',
    'Variável',
    'Hewett, 2005',
    ARRAY['drop jump test', 'dynamic knee valgus test'],
    ARRAY['Esportiva', 'Joelho', 'Preventivo'],
    'functional_test',
    '[{"id": "valgus_quality", "label": "Qualidade do Valgo", "type": "select", "options": ["Bom", "Moderado", "Ruim"], "required": true}]'::jsonb
),
(
    'Tuck Jump Assessment',
    'Tuck Jump Assessment',
    'Esportiva',
    'Joelho',
    'Avaliar padrões de movimento em saltos repetitivos',
    '10 saltos contínuos puxando joelhos ao peito.',
    'Valgo, assimetria, fadiga, barulho na aterrissagem.',
    'Variável',
    'Myer, 2011',
    ARRAY['tuck jump assessment', 'knee valgus jump test'],
    ARRAY['Esportiva', 'Joelho', 'Pliometria'],
    'functional_test',
    '[{"id": "score", "label": "Pontuação de Falhas", "type": "number", "min": 0, "max": 10, "required": true}]'::jsonb
),
(
    'Lunge Test (Knee to Wall)',
    'Lunge Test (Knee to Wall)',
    'Esportiva',
    'Tornozelo',
    'Mensurar amplitude de dorsiflexão',
    'Tentar tocar o joelho na parede sem tirar calcanhar.',
    'Distância reduzida comparada ao lado oposto.',
    'Variável',
    'Bennell, 1998',
    ARRAY['knee to wall test', 'ankle dorsiflexion test'],
    ARRAY['Esportiva', 'Tornozelo', 'Mobilidade'],
    'functional_test',
    '[{"id": "distance_cm", "label": "Distância (cm)", "type": "number", "unit": "cm", "required": true}]'::jsonb
);
