name: Schema Diff

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  schema-diff:
    name: Generate Schema Diff
    runs-on: ubuntu-latest
    steps:
      - name: Generate Schema Diff
        uses: neondatabase/schema-diff-action@v6.0.4
        with:
          base_branch: production
          compare_branch: preview/pr-${{ github.event.number }}
          api_key: ${{ secrets.NEON_API_KEY }}
          project_id: ${{ vars.NEON_PROJECT_ID }}
